### ISSUE TITLE
Issue with convictions

### ISSUE THREAD

**Issue by skrimxyz** [Project-Sloth/ps-mdt#1]
I will post a screenshot with the issue

![image](https://user-images.githubusercontent.com/92062857/161375251-5ec2fe4d-32db-4a64-8f6c-3dc8b77ba80d.png)

**Comment by MonkeyWhisper** [comment]
> I will post a screenshot with the issue
> 
> ![image](https://user-images.githubusercontent.com/92062857/161375251-5ec2fe4d-32db-4a64-8f6c-3dc8b77ba80d.png)

Is this still happening?

**Comment by skrimxyz** [comment]
> > I will post a screenshot with the issue
> > ![image](https://user-images.githubusercontent.com/92062857/161375251-5ec2fe4d-32db-4a64-8f6c-3dc8b77ba80d.png)
> 
> Is this still happening?

Yup

**Comment by JoeSzymkowiczFiveM** [comment]
Should be fixed with latest push. Try now.
