### ISSUE TITLE
Data too long for column

### ISSUE THREAD

**Issue by OfficialRDB** [Project-Sloth/ps-mdt#107]
I believe they tried to add a incidents.

![Capture](https://user-images.githubusercontent.com/50579206/194232909-6bca5faf-8818-4ce6-a5b3-3ec9b58f4929.PNG)

**Comment by CarlBishop** [comment]
Max character for title column in table mdt_incidents is 50 char

`  `title` varchar(50) NOT NULL DEFAULT '0',`

You can increase it from the sql

**Comment by OfficialRDB** [comment]
> Max character for title column in table mdt_incidents is 50 char
> 
> ` `title` varchar(50) NOT NULL DEFAULT '0',`
> 
> You can increase it from the sql

Is there not just a option to make it max 50 in the script ? I can put it to 100, but if someone puts in 100 chars it comes back with the same.

I know it's stupid but some are trying to be funny.
So if I know where to make that max char check otherwise return a notify message.

I'll try a maxlength="number" on the input.
