### ISSUE TITLE
No way to remove charges from current charges

### ISSUE THREAD

**Issue by nggcasey** [Project-Sloth/ps-mdt#108]
There's no way to remove charges when you've added them - It's beyond my skills to fix that.

![image](https://user-images.githubusercontent.com/60057103/194434541-5d67dff2-720d-4134-b4ff-5cd439b3a18e.png)

**Comment by QBLes** [comment]
find the charge in the list and right click it... this removes the charge...

**Comment by nggcasey** [comment]
ah
