### ISSUE TITLE
Info from dispatch goes to all jobs

### ISSUE THREAD

**Issue by CreelEU** [Project-Sloth/ps-mdt#13]
When getting info from dispatch like "Shoots Fired" and it's only selected for "police" in qb-dispatch, it goes to all jobs (police and ambulance only tested
![a0ba845d3dbee7ad0c5bd750b30e9fc2](https://user-images.githubusercontent.com/63866637/163046470-0e003594-92f3-4298-936c-fb14e7c80fb8.png)
![b5f128b67e47ac0536298daffca8098d](https://user-images.githubusercontent.com/63866637/163046475-e4be4d49-e214-48e2-93fb-518d22cf0cbb.png)
)

**Comment by pushkart2** [comment]
fixed it in recent commit (doesnt work if jobs are changed in game)

**Comment by CreelEU** [comment]
> fixed it in recent commit (doesnt work if jobs are changed in game)

Thanks! And what do you mean about "changed in game", do you mean if a player goes from police to ambulance that it will show in the mdt for the newly ambulance aswell?

**Comment by pushkart2** [comment]
> > fixed it in recent commit (doesnt work if jobs are changed in game)
> 
> Thanks! And what do you mean about "changed in game", do you mean if a player goes from police to ambulance that it will show in the mdt for the newly ambulance aswell?

no, so imagine, you are a cop and you get a alert, it will show up in mdt and if you change job to ambulance, it will still show. But now if another alert comes when you are ambulance, it wont show in mdt and if you change to police, it wont still show.

**Comment by pushkart2** [comment]
I will try to find a better of way of doing it, but for now if you have one job, it should work fine

**Comment by CreelEU** [comment]
> > > fixed it in recent commit (doesnt work if jobs are changed in game)
> > 
> > 
> > Thanks! And what do you mean about "changed in game", do you mean if a player goes from police to ambulance that it will show in the mdt for the newly ambulance aswell?
> 
> no, so imagine, you are a cop and you get a alert, it will show up in mdt and if you change job to ambulance, it will still show. But now if another alert comes when you are ambulance, it wont show in mdt and if you change to police, it wont still show.

Ah i see, so for the time being, if a cop changes to ambulance, it's best for them to relog after changing the job?

**Comment by pushkart2** [comment]
> > > > fixed it in recent commit (doesnt work if jobs are changed in game)
> > > 
> > > 
> > > Thanks! And what do you mean about "changed in game", do you mean if a player goes from police to ambulance that it will show in the mdt for the newly ambulance aswell?
> > 
> > 
> > no, so imagine, you are a cop and you get a alert, it will show up in mdt and if you change job to ambulance, it will still show. But now if another alert comes when you are ambulance, it wont show in mdt and if you change to police, it wont still show.
> 
> Ah i see, so for the time being, if a cop changes to ambulance, it's best for them to relog after changing the job?
Until we find a better way to do it, might needs a rewrite of the dispatch portion in mdt but lets see
yep

**Comment by CreelEU** [comment]
> > > > > fixed it in recent commit (doesnt work if jobs are changed in game)
> > > > 
> > > > 
> > > > Thanks! And what do you mean about "changed in game", do you mean if a player goes from police to ambulance that it will show in the mdt for the newly ambulance aswell?
> > > 
> > > 
> > > no, so imagine, you are a cop and you get a alert, it will show up in mdt and if you change job to ambulance, it will still show. But now if another alert comes when you are ambulance, it wont show in mdt and if you change to police, it wont still show.
> > 
> > 
> > Ah i see, so for the time being, if a cop changes to ambulance, it's best for them to relog after changing the job?
> > Until we find a better way to do it, might needs a rewrite of the dispatch portion in mdt but lets see
> > yep

Alright! Thanks, I'll try this tomorrow and report! :)

**Comment by pushkart2** [comment]
> > > > fixed it in recent commit (doesnt work if jobs are changed in game)
> > > 
> > > 
> > > Thanks! And what do you mean about "changed in game", do you mean if a player goes from police to ambulance that it will show in the mdt for the newly ambulance aswell?
> > 
> > 
> > no, so imagine, you are a cop and you get a alert, it will show up in mdt and if you change job to ambulance, it will still show. But now if another alert comes when you are ambulance, it wont show in mdt and if you change to police, it wont still show.
> 
> Ah i see, so for the time being, if a cop changes to ambulance, it's best for them to relog after changing the job?

For time being until a better solution is found or a rewrite of the whole dispatch section in mdt. Probably an enhancement
