### ISSUE TITLE
Weapons Tab

### ISSUE THREAD

**Issue by TheCrypticOG** [Project-Sloth/ps-mdt#131]
When you register a weapon to the database you get this notification in the staff logs of the mdt.

• A weapon with the serial number (50EqR1ek762tAuJ) failed to be added to the weapon information database by Mac Thompson

Then when you search for a weapon by serial number every weapon shows up. It does not filter any out that does not match what you entered.

https://i.imgur.com/Dfk4Vzd.png

Searched that serial number and both weapons appeared

**Comment by JoeSzymkowiczFiveM** [comment]
I used the following test, and information inserted correctly.
`exports['ps-mdt']:CreateWeaponInfo('50EqR1ek762tAuJ', 'https://gastatic.com/digest/wp-content/uploads/2019/11/MossbergMC1SC.jpg', 'Notes here', 'Bill Hammerdunk', '2', 'Pistol')`

![image](https://user-images.githubusercontent.com/70592880/204107182-5569f4ce-2d68-4540-ba70-82bfee46833c.png)

Fixing the searching issue right now and will push in a couple minutes.
