### ISSUE TITLE
Adding incident

### ISSUE THREAD

**Issue by iamthegoat69696996969** [Project-Sloth/ps-mdt#132]
I am trying to add this incident and it will not work
![image](https://user-images.githubusercontent.com/94282104/203730539-61544943-3baf-4492-b05f-b6a683f1c5a4.png)

**Comment by JoeSzymkowiczFiveM** [comment]
I tried saving the same title, and the server console is reporting the title is too long. Please report any errors in the client or server consoles when reporting issues. You can increase the title column in the incidents table.
