### ISSUE TITLE
MDT.sql Error

### ISSUE THREAD

**Issue by NokaAngel** [Project-Sloth/ps-mdt#138]
CREATE TABLE IF NOT EXISTS `mdt_data` (  
`id` int(11) NOT NULL AUTO_INCREMENT,  
`cid` VARCHAR(20) DEFAULT NULL,  
`information` MEDIUMTEXT DEFAULT NULL,  
`tags` TEXT NOT NULL,  `gallery` TEXT NOT NULL,  
`jobtype` VARCHAR(25) DEFAULT 'police',  
`pfp` TEXT DEFAULT NULL,  
`fingerprint` VARCHAR(50) DEFAULT NULL,  PRIMARY KEY (`cid`),  KEY 
`id` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

Had MySQL saying
#1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

I am using MySQL version 8.0.31.

**Comment by bennimedia** [comment]
i have the same problem

**Comment by LV-Soft** [comment]
Use this query

```
CREATE TABLE IF NOT EXISTS `mdt_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(20) NOT NULL,
  `information` MEDIUMTEXT DEFAULT NULL,
  `tags` TEXT NOT NULL,
  `gallery` TEXT NOT NULL,
  `jobtype` VARCHAR(25) DEFAULT 'police',
  `pfp` TEXT DEFAULT NULL,
  `fingerprint` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`cid`),
  KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by bennimedia** [comment]
> Use this query
> 
> ```
> CREATE TABLE IF NOT EXISTS `mdt_data` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `cid` VARCHAR(20) NOT NULL,
>   `information` MEDIUMTEXT DEFAULT NULL,
>   `tags` TEXT NOT NULL,
>   `gallery` TEXT NOT NULL,
>   `jobtype` VARCHAR(25) DEFAULT 'police',
>   `pfp` TEXT DEFAULT NULL,
>   `fingerprint` VARCHAR(50) DEFAULT NULL,
>   PRIMARY KEY (`cid`),
>   KEY `id` (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
> ```

Thank You,
now when i open the mdt i have this error in the console:
![grafik](https://user-images.githubusercontent.com/85938749/210579183-58f124ca-5a1a-4142-82b8-fa9ac169d986.png)

**Comment by LV-Soft** [comment]
Weird, it's an error in [Ox MySQL](https://github.com/overextended/oxmysql).. do you have last version of OxMySQL?

**Comment by LV-Soft** [comment]
Weird, try upgrading your MySQL to MariaDB and update your  [Ox MySQL](https://github.com/overextended/oxmysql) to the last version.
