### ISSUE TITLE
ActiveUnit data is not updated accurately

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#156]
When you open the MDT, there is a stale data issue happening with the Active Units section under the Dispatch tab on the Dashboard.

There are a handful of issues that are caused by this stale data issue:
1. A person will not show in the active units list, until they have opened the MDT themselves
   - For example: if person 1 and person 2 are cops. And person 1 opens his MDT, he will only see person 1 in the active unit tab. Once person 2 opens his MDT, then both person 1 and person 2 will be displayed.
2. If you change your radio channel, the displayed channel next to a persons name will potentially show the previous channel they had set. The number will not update until they have reopened their mdt.
 - For example: if person 1 is on Channel1 and then he changes his radio to Channel2. Person2 looks at active units and they will see person1 is on Channel1. The number will not update until Person1 reopens their mdt, only then will it display correctly.
3. The callsign and onduty fields also have this same issue as described above, it will potentially display stale data.

We narrowed down the source of this issue to how the MDT activeUnits are populated when opening the MDT.
In server/main.lua - 'mdt:server:openMDT', we update the activeUnits list ONLY with the current players information at the time of opening the MDT. Because of this, it leads to the data staleness described above. The information for this player will only update everytime they open the MDT. So if they make any changes to their radio, callsign, duty, or jobtype and don't open their MDT, this will lead to others viewing incorrect data.

Potential solutions:
- On open of MDT, fetch all players of the given jobs we want to populate (police, ems, etc), get their data from QBCore and then update the activeUnits list. This should ensure that the data shown is up to date. The downside of this approach, is that this could be a bit of a heavy operation and would create perf impacts on the server. This is a relatively quick and easy solution to implement.
- Another possible solution thats a bit more involved, when a player loads in and is of the job types we care about, we could immediately add their information to the activeUnits list. This would address showing people in activeUnits right away without them needing to first open the MDT. To address any changes to their data, we could set up event handlers for each of the fields we care about (radio, callsign, duty, jobtype) and then selectively update the activeUnits list when those are changed.
   - For example: Player 1 logs on as a cop. 
      - We have an onPlayerLoaded event that immediately populates the activeUnits with their current information
      - Player 1 turns on their radio and changes to channel 1. We would have an event handler listening for this change and would update this field in the activeUnits list
      - Player 1 clocks off duty, again we listen for that, handle the event and update the list.
      - Same would hold true for if they change jobs or callsigns
  - This is probably a more performant solution as compared to the first one, a tad bit more involved to implement however.

```
Referencing how activeUnits is populated today:
activeUnits[PlayerData.citizenid] = {
		cid = PlayerData.citizenid, -- this wont change
		callSign = PlayerData.metadata['callsign'],  -- this field could change and be stale
		firstName = PlayerData.charinfo.firstname:sub(1,1):upper()..PlayerData.charinfo.firstname:sub(2), -- this wont change
		lastName = PlayerData.charinfo.lastname:sub(1,1):upper()..PlayerData.charinfo.lastname:sub(2), -- this wont change
		radio = Radio,  -- this field could change and be stale
		unitType = PlayerData.job.name,  -- this field could change and be stale
		duty = PlayerData.job.onduty  -- this field could change and be stale
	}
```

I wanted to run this by folks to see if there are other solutions that might solve this better. I am currently leaning towards implementing the second proposed solution.

**Comment by BackSH00TER** [comment]
@MonkeyWhisper I'd like your thoughts on the above issue when you have time. I'm happy to implement the solution, just want to make sure I have buy in before I start.

**Comment by MonkeyWhisper** [comment]
> @MonkeyWhisper I'd like your thoughts on the above issue when you have time. I'm happy to implement the solution, just want to make sure I have buy in before I start.

Hi, 

Yes, that'll be great if we can get a PR to fix those issues, we aren't even aware of those. 

Most of these issues aren't being reported by the community even though nearly 2,500 server use this resource. 

Thank you very much for taking initiative on this! 

![image](https://user-images.githubusercontent.com/82112471/222932159-e3447f38-dfc8-4c76-8380-2f17e08c3ff4.png)

**Comment by zCursorz** [comment]
I suppose this may be the cause to my issue with the new clock-in/out feature of the MDT. If you clock in on MDT then set your job to unemployed and fly out you will still receive the discord notification although you are no longer police/leo. 

I guess as you don't open the MDT again prior to clocking in it does not update locally? 

@BackSH00TER 

![image](https://user-images.githubusercontent.com/82294205/230804435-acb0a933-9de1-42ac-99cf-43e702774249.png)

**Comment by DannyHD001** [comment]
Hi, I am also seeing this issue. Has this been fixed or what is the status?

**Comment by MonkeyWhisper** [comment]
> Hi, I am also seeing this issue. Has this been fixed or what is the status?

What do you mean what is the status? Do you see this as completed? No, so there's your answer.

If you want to fix it, go ahead, send a PR.

**Comment by DannyHD001** [comment]
Oh, excuse me for asking.

**Comment by MonkeyWhisper** [comment]
> When you open the MDT, there is a stale data issue happening with the Active Units section under the Dispatch tab on the Dashboard.
> 
> There are a handful of issues that are caused by this stale data issue:
> 
> 1. A person will not show in the active units list, until they have opened the MDT themselves
>    
>    * For example: if person 1 and person 2 are cops. And person 1 opens his MDT, he will only see person 1 in the active unit tab. Once person 2 opens his MDT, then both person 1 and person 2 will be displayed.
> 2. If you change your radio channel, the displayed channel next to a persons name will potentially show the previous channel they had set. The number will not update until they have reopened their mdt.
> 
> * For example: if person 1 is on Channel1 and then he changes his radio to Channel2. Person2 looks at active units and they will see person1 is on Channel1. The number will not update until Person1 reopens their mdt, only then will it display correctly.
> 
> 3. The callsign and onduty fields also have this same issue as described above, it will potentially display stale data.
> 
> We narrowed down the source of this issue to how the MDT activeUnits are populated when opening the MDT. In server/main.lua - 'mdt:server:openMDT', we update the activeUnits list ONLY with the current players information at the time of opening the MDT. Because of this, it leads to the data staleness described above. The information for this player will only update everytime they open the MDT. So if they make any changes to their radio, callsign, duty, or jobtype and don't open their MDT, this will lead to others viewing incorrect data.
> 
> Potential solutions:
> 
> * On open of MDT, fetch all players of the given jobs we want to populate (police, ems, etc), get their data from QBCore and then update the activeUnits list. This should ensure that the data shown is up to date. The downside of this approach, is that this could be a bit of a heavy operation and would create perf impacts on the server. This is a relatively quick and easy solution to implement.
> * Another possible solution thats a bit more involved, when a player loads in and is of the job types we care about, we could immediately add their information to the activeUnits list. This would address showing people in activeUnits right away without them needing to first open the MDT. To address any changes to their data, we could set up event handlers for each of the fields we care about (radio, callsign, duty, jobtype) and then selectively update the activeUnits list when those are changed.
>   
>   * For example: Player 1 logs on as a cop.
>     
>     * We have an onPlayerLoaded event that immediately populates the activeUnits with their current information
>     * Player 1 turns on their radio and changes to channel 1. We would have an event handler listening for this change and would update this field in the activeUnits list
>     * Player 1 clocks off duty, again we listen for that, handle the event and update the list.
>     * Same would hold true for if they change jobs or callsigns
>   * This is probably a more performant solution as compared to the first one, a tad bit more involved to implement however.
> 
> ```
> Referencing how activeUnits is populated today:
> activeUnits[PlayerData.citizenid] = {
> 		cid = PlayerData.citizenid, -- this wont change
> 		callSign = PlayerData.metadata['callsign'],  -- this field could change and be stale
> 		firstName = PlayerData.charinfo.firstname:sub(1,1):upper()..PlayerData.charinfo.firstname:sub(2), -- this wont change
> 		lastName = PlayerData.charinfo.lastname:sub(1,1):upper()..PlayerData.charinfo.lastname:sub(2), -- this wont change
> 		radio = Radio,  -- this field could change and be stale
> 		unitType = PlayerData.job.name,  -- this field could change and be stale
> 		duty = PlayerData.job.onduty  -- this field could change and be stale
> 	}
> ```
> 
> I wanted to run this by folks to see if there are other solutions that might solve this better. I am currently leaning towards implementing the second proposed solution.

https://github.com/Project-Sloth/ps-mdt/pull/299

Can you possible test this with your player base?

**Comment by MonkeyWhisper** [comment]
Closed, we will get this corrected on v2
