### ISSUE TITLE
unable to edit there warrant status etc

### ISSUE THREAD

**Issue by MarcusPlayz517** [Project-Sloth/ps-mdt#16]
once you save the report the first time you are unable to edit there warrant status or if they are guilty or not etc, watch the clip in the LJ Labs discord for more info: https://discord.com/channels/897744257237000222/900180032935325707/962931262392266842

I can give so many reasons why this is incorrect, but the main one is. when placing a player on a active warrant its impossible to remove it. after removing the warrant from the incident and clicking save then reopening the incident the warrant is active again.

messages from discord support chat:
**Monkey | Protector of the Lab — 04/11/2022**
How is this incorrect?
**MarcusPlayz517 — 04/11/2022**
after you save it the first time you can't edit it again, e.g you can't remove/add warrants, guilty, processed or associated. you also can't add more chargers or criminals

**Comment by M1dNigh** [comment]
having the same issue

**Comment by MarcusPlayz517** [comment]
fixed with this PR: https://github.com/Project-Sloth/qb-mdt/pull/11
