### ISSUE TITLE
[ISSUE] The Known Conviction Section and Under Profiles Scrolling Through names

### ISSUE THREAD

**Issue by NikoClapz19** [Project-Sloth/ps-mdt#162]
When attempting to scroll through the Known Convictions of the Civilian i can't see what they are

https://cdn.discordapp.com/attachments/900180032935325707/1082981055751000214/2023-03-08_05-59-32.mp4

2.) The citizen ID for each profile is misplaced and can't really see it properly unless you actually click on the profile

**Comment by MonkeyWhisper** [comment]
Cannot duplicate, working as intended

![image](https://user-images.githubusercontent.com/82112471/224071137-8481c507-0ffd-4161-81a9-c33bd69b1aaa.png)
