### ISSUE TITLE
EMS Profile Save Wipes Licences

### ISSUE THREAD

**Issue by KodeShinju** [Project-Sloth/ps-mdt#163]
Upon using 1.7 - if EMS try to edit a profile, it will wipe the player's licenses and actually revoke them through QBCore. 
![image](https://user-images.githubusercontent.com/37993138/224185140-75d59d12-6b94-447b-b933-4e66d9a34a7c.png)

**Comment by MonkeyWhisper** [comment]
Send a video of this happening along with showing F8 and server console for any errors

**Comment by MonkeyWhisper** [comment]
Issue has been duplicated and it is happening

**Comment by MonkeyWhisper** [comment]
https://medal.tv/games/gta-v/clips/ZnOb1bFcmY7zP/OmB3c6VcxGUM?invite=cr-MSxlUzIsNTI3MzEyNDUs

**Comment by MonkeyWhisper** [comment]
This isn't an issue, this was meant to be like so after reviewing the code,  the saveProfile() function, there is a check to see if the user's role is "ambulance" and if so, their license is revoked by setting the isLicensed property to false this is to  prevent ambulance from editing the player's profile

**Comment by KodeShinju** [comment]
So this is intended then? I'm trying to understand that - because EMS should be able to edit profiles on their end? Also it feels weird to make it lose licenses versus just wiping whatever "ambulance" type players are inputting.

**Comment by MonkeyWhisper** [comment]
Why will ambulance have the need to edit anything on a profile? They don't need anything on it, matter of fact, they shouldn't need the Profile tab at all.

**Comment by KodeShinju** [comment]
To literally look up patient names. EMS can use the profiles for multitudes of things - just as PD would, would like seeing reports that involve persons in medical. EMS using profiles could result in better medical roleplay for writing lasting conditions making in-game reference easier, i.e. Patient has morphine allergy. Patient has history of abusing painkillers, be advised. Patient is hemophiliac and requires factor V transfusions. With the line of logic I'm hearing, it seems that EMS shouldn't have an MDT whatsoever.

**Comment by MonkeyWhisper** [comment]
We will be removing the Profiles from EMS side.
