### ISSUE TITLE
NUI Call back Error

### ISSUE THREAD

**Issue by PhantomAwe** [Project-Sloth/ps-mdt#165]
Hi I have recently updated the MDT been using ps-mdt for a while and thought to update it but when updating and trying to access a profile I am getting 

"script:ps-mdt error during NUI callback getProfileData: @ps-mdt/client/main.lua:334: attempt to index nil value (local 'vehDate')

it is connected with "result.vehicles[i]['model'] = vehData["name"]" I commented this out and now works fine but if I am correct this loads the car model on peoples profiles along with their licence plate?

what would I need to do to get this to work?

**Comment by MonkeyWhisper** [comment]
This is not for support. 

ps-mdt is working fine.
