### ISSUE TITLE
vehicleOwner error

### ISSUE THREAD

**Issue by JordanBScott** [Project-Sloth/ps-mdt#167]
I have recently updated ps-mdt to use the new features and one being the WolfknightRadar plate detection with No Drivers License reports. Sometimes when an officer is driving around their scanner will scan a plate, but the alert for no drivers license report comes up on  the screen. An error just shows up over and over again on the txAdmin console (see picture).
The officers don't realize this is happening since there is no report. Just in the console.

This is line 61 from the error:
TriggerClientEvent('QBCore:Notify', src, 'NO DRIVERS LICENCE | Registered Owner: '..vehicleOwner..' | Plate: '..plate, 'error', Config.WolfknightNotifyTime)

I didn't upload a video since nothing comes up on the players screen. Just in the console as an error.

![image](https://user-images.githubusercontent.com/99845881/224526292-b1be435d-6529-4664-92a0-c648bc3c24ad.png)

**Comment by BackSH00TER** [comment]
Looking at the code, its assuming vehicleOwner will always be defined, however it won't be. 
GetVehicleOwner, reads from the player vehicles table. 

Anytime the radar triggers on a plate that is not owned by a player(not in the db) vehicleOwner will be nil, and you can't concatenate a nil value. 

Easy fix is to just do `if driversLicense == false and vehicleOwner then ...`

**Comment by MonkeyWhisper** [comment]
Thanks, also, you didn't set this setting.

-- To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'. 
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/commit/13dfc17f77ff90480d6c857af44647b6d32f2141
