### ISSUE TITLE
Error: Searching Player MDT

### ISSUE THREAD

**Issue by uShifty** [Project-Sloth/ps-mdt#17]
When searching a player in the mdt I get a error for an illegal mix of collations, The solution would of course be to make the database use the same collation all around but I cannot convert the players table because of a index key "UK_playervehicles_plate "

https://cdn.discordapp.com/attachments/950959271678464051/956713184117534780/unknown.png - In game server error
https://cdn.discordapp.com/attachments/950959271678464051/956713190807470130/unknown.png - Database error converting to "utf8mb4_general_ci"

**Comment by Zotactiks** [comment]
What version of Oxmysql you using?

**Comment by uShifty** [comment]
> What version of Oxmysql you using?

2.1.1

**Comment by pushkart2** [comment]
I am not able to replicate this issue. Has to do something with the foreign key constraints. 
@JoeSzymkowiczFiveM  we need to rework the sql file

**Comment by justBMR** [comment]
Hey guys,
I downloaded the latest version of qb-mdt, copied it to my server resources and made sure qb-mdt in the server.cfg. When I try to search for a player, it gives the error I sent in the print. I already installed a new qbcore base and just started the mdt resource, but the error is the same. I deleted all MDT tables from the database and re-executed the sql file provided in the resource. Nothing fixed so far.

Greetings and thank you very much for your project
![error mdt](https://user-images.githubusercontent.com/93486510/166107410-d2fca986-12fb-4250-9703-655a0e6b31e0.png)

**Comment by ghost** [comment]
> Hey guys, I downloaded the latest version of qb-mdt, copied it to my server resources and made sure qb-mdt in the server.cfg. When I try to search for a player, it gives the error I sent in the print. I already installed a new qbcore base and just started the mdt resource, but the error is the same. I deleted all MDT tables from the database and re-executed the sql file provided in the resource. Nothing fixed so far.
> 
> Greetings and thank you very much for your project ![error mdt](https://user-images.githubusercontent.com/93486510/166107410-d2fca986-12fb-4250-9703-655a0e6b31e0.png)

I have the exact same error, did you get it fix it? i have found nothing i search everywhere

**Comment by ghost** [comment]
> Hey guys, I downloaded the latest version of qb-mdt, copied it to my server resources and made sure qb-mdt in the server.cfg. When I try to search for a player, it gives the error I sent in the print. I already installed a new qbcore base and just started the mdt resource, but the error is the same. I deleted all MDT tables from the database and re-executed the sql file provided in the resource. Nothing fixed so far.
> 
> Greetings and thank you very much for your project ![error mdt](https://user-images.githubusercontent.com/93486510/166107410-d2fca986-12fb-4250-9703-655a0e6b31e0.png)

Hey mate, i just fix it, it was a dumb error, in my case i was importing all the sql tables at once.
What i did is create each table one by one
Let me know if that works for you too :)

**Comment by uShifty** [comment]
> > Hey guys, I downloaded the latest version of qb-mdt, copied it to my server resources and made sure qb-mdt in the server.cfg. When I try to search for a player, it gives the error I sent in the print. I already installed a new qbcore base and just started the mdt resource, but the error is the same. I deleted all MDT tables from the database and re-executed the sql file provided in the resource. Nothing fixed so far.
> > Greetings and thank you very much for your project ![error mdt](https://user-images.githubusercontent.com/93486510/166107410-d2fca986-12fb-4250-9703-655a0e6b31e0.png)
> 
> Hey mate, i just fix it, it was a dumb error, in my case i was importing all the sql tables at once. What i did is create each table one by one Let me know if that works for you too :)

Just tried this but it did not work for me 😢This has to be the most stupidest issue ive dealt this

**Comment by uShifty** [comment]
Converting the MDT tables to use the collation utf8mb4_unicode_ci  seems to have fixed the error for me!

**Comment by MonkeyWhisper** [comment]
Great!
