### ISSUE TITLE
cant edit any info on profiles

### ISSUE THREAD

**Issue by FrequencyRoleplay** [Project-Sloth/ps-mdt#170]
cant edit anything

**Comment by FrequencyRoleplay** [comment]
also profile tab not populating citizen ID, DOB and all that info

**Comment by FrequencyRoleplay** [comment]
Found a fix , Since i dont use qb apartments. 

I went into mdt server lua and commented out 2 lines a line 262


	-- if apartmentData then
	-- 	apartmentData = apartmentData[1].label .. ' (' ..apartmentData[1].name..')'
	-- end

**Comment by MonkeyWhisper** [comment]
This isn't an issue with us clearly.
