### ISSUE TITLE
Integrate Mugshots

### ISSUE THREAD

**Issue by MonkeyWhisper** [Project-Sloth/ps-mdt#172]
Integrate config only with mugshots, perhaps using as a config option turned off by default
Take picture and send set as profile image, just front image 
https://github.com/CQC-Scripting/cqc-mugshot

If you're not going to be part of the solution or integration of this issue, do not comment.

**Comment by DooubleTap** [comment]
that would be amazing !!

**Comment by MonkeyWhisper** [comment]
Started working on this rough start, everyone feel free to edit and submit PR

https://github.com/LeSiiN/ps-mdt/tree/cqc-mugshot

**Comment by lenzh** [comment]
so i got it working:

What i did was i modified CQC-mugshots server.lua to and i enabled Config.CQCMDT

```
RegisterNetEvent('cqc-mugshot:server:MDTupload', function(citizenid, MugShotURLs)
    MugShots[citizenid] = MugShotURLs
    local cid = citizenid
    
    if Config.CQCMDT then
        -- TriggerEvent('cqc-mdt:server:updateMugShotForCitizen',citizenid, MugShotURLs)
        TriggerEvent('mdt:server:saveMugshot', cid, MugShotURLs)
    end
end)
```
and added 
```
RegisterNetEvent("mdt:server:saveMugshot", function(cid, MugShotURLs)
	MySQL.Async.insert('INSERT INTO mdt_data (cid, pfp, gallery, tags) VALUES (:cid, :pfp, :gallery, :tags) ON DUPLICATE KEY UPDATE cid = :cid,  pfp = :pfp, tags = :tags, gallery = :gallery', {
		cid = cid,
		pfp = MugShotURLs[1],
		tags = json.encode(tags),
		gallery = json.encode(MugShotURLs),
	})
end)
```
to ps-mdt server side

within my jail function i have it so it executes a jail command where cqc is putin already but if you manually take a mugshot using the camera of cqc-mugshot it will work aswell

**Comment by MonkeyWhisper** [comment]
> so i got it working:
> 
> What i did was i modified CQC-mugshots server.lua to and i enabled Config.CQCMDT
> 
> ```
> RegisterNetEvent('cqc-mugshot:server:MDTupload', function(citizenid, MugShotURLs)
>     MugShots[citizenid] = MugShotURLs
>     local cid = citizenid
>     
>     if Config.CQCMDT then
>         -- TriggerEvent('cqc-mdt:server:updateMugShotForCitizen',citizenid, MugShotURLs)
>         TriggerEvent('mdt:server:saveMugshot', cid, MugShotURLs)
>     end
> end)
> ```
> 
> and added
> 
> ```
> RegisterNetEvent("mdt:server:saveMugshot", function(cid, MugShotURLs)
> 	MySQL.Async.insert('INSERT INTO mdt_data (cid, pfp, gallery, tags) VALUES (:cid, :pfp, :gallery, :tags) ON DUPLICATE KEY UPDATE cid = :cid,  pfp = :pfp, tags = :tags, gallery = :gallery', {
> 		cid = cid,
> 		pfp = MugShotURLs[1],
> 		tags = json.encode(tags),
> 		gallery = json.encode(MugShotURLs),
> 	})
> end)
> ```
> 
> to ps-mdt server side
> 
> within my jail function i have it so it executes a jail command where cqc is putin already but if you manually take a mugshot using the camera of cqc-mugshot it will work aswell

Hi,

Please send a PR for this

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/pull/187
