### ISSUE TITLE
Display Issues Format

### ISSUE THREAD

**Issue by MonkeyWhisper** [Project-Sloth/ps-mdt#173]
![image](https://user-images.githubusercontent.com/82112471/224855354-e252ddb8-a139-4e18-811c-0d15a660412b.png)
![image](https://user-images.githubusercontent.com/82112471/224855487-d0b8e5e7-4ac6-4fea-85c9-cd45f1c2d281.png)

If you're not going to be part of the solution or integration of this issue, do not comment.

**Comment by DooubleTap** [comment]
it would be AWESOME to have a +/- (Zoom) function to edit the resolution of the mdt <3

**Comment by MonkeyWhisper** [comment]
@LeSiiN This started happening after I merged that PR from yours with the Delete, can you just take a closer look at it and see if you find anything? 

I'd appreciate it

**Comment by MonkeyWhisper** [comment]
So far two users have reported this on a 1080, I have been unable to duplicate this

**Comment by LeSiiN** [comment]
i'll check on it, but if i remember correctly i had that aswell but before i did anything to the mdt

**Comment by LeSiiN** [comment]
So after some style.css edits it looks like this ( 1920x1080 )
Before i did that, i removed my PR's from the other day and checked if that still happens, it does thats why i started the css edits.
https://youtu.be/Ai05Lbn42zE - didnt tested any other resolution
https://i.imgur.com/3QEiNqH.jpeg - just made every item inside the right container a little higher so it does actually show the full words

**Comment by MonkeyWhisper** [comment]
Yeah, thank you

Still looks like this is cut off 
![image](https://user-images.githubusercontent.com/82112471/225095722-10579126-8b02-47c8-8865-744ac9e1bdab.png)

You know how it opens up for charges? I wonder if we should just do that for Known Convictions and for Incidents have like a little icon eye next to it then those open up like how you would add a charge, so it's bigger, compared to small like that

**Comment by MonkeyWhisper** [comment]
> Yeah, thank you
> 
> Still looks like this is cut off ![image](https://user-images.githubusercontent.com/82112471/225095722-10579126-8b02-47c8-8865-744ac9e1bdab.png)
> 
> You know how it opens up for charges? I wonder if we should just do that for Known Convictions and for Incidents have like a little icon eye next to it then those open up like how you would add a charge, so it's bigger, compared to small like that

**Comment by LeSiiN** [comment]
so instead of a extra row like the other ones like vehicle , licenes and stuff just make a clickable eye icon and let it open another page with all the known convictions/incidents? did i understand that correct? -> so its not that ,,overgrown'' sry missing english words XD

and what about the citizen id ( the screen ) cant find the spot where its cut off

**Comment by LeSiiN** [comment]
im going to start my test server and check it, maybe the screen is dogwater and it just looks like that because of the screen

**Comment by LeSiiN** [comment]
https://youtu.be/AtdQ6pHkzH0 - looks fine for me, let me create another character and check again

**Comment by LeSiiN** [comment]
https://youtu.be/fK2CBf_ytbA - here again with another character, cant find any issue with it beeing cut off

**Comment by LeSiiN** [comment]
Going offline for today, gonna check tomorrow, and then gonna make a PR for the changes i did as soon as monkey says so

**Comment by MonkeyWhisper** [comment]
> so instead of a extra row like the other ones like vehicle , licenes and stuff just make a clickable eye icon and let it open another page with all the known convictions/incidents? did i understand that correct? -> so its not that ,,overgrown'' sry missing english words XD
> 
> and what about the citizen id ( the screen ) cant find the spot where its cut off

Reopened issue, I closed it by accident. 

Yup, exactly like that. For example, how how it opens the Charges or another page, like this 

https://cdn.discordapp.com/attachments/1081275377604902972/1081280650277048422/FiveM_b2699_GTAProcess_gppJpV4Xnp.gif

**Comment by LeSiiN** [comment]
okay so i did that for know
https://i.imgur.com/35Tbh2U.png
but im totally knew to html/js and css so i wouldnt actually want to do that, because i dont want to mess something up, just a look on how it could look

**Comment by MonkeyWhisper** [comment]
@LeSiiN That's perfect, great job

**Comment by MonkeyWhisper** [comment]
This is now on the developer branch for editing 

https://github.com/Project-Sloth/ps-mdt/tree/display

**Comment by MonkeyWhisper** [comment]
It has been semi fixed, for now
