### ISSUE TITLE
Respond (Attached units) not updating

### ISSUE THREAD

**Issue by DooubleTap** [Project-Sloth/ps-mdt#175]
I cannot, for the life of me attach myself to an incident, or a call: 
![image](https://user-images.githubusercontent.com/3772136/224918678-e7a0b7f8-18a2-4575-8dd1-d2a90c5a97d4.png)

**Comment by Pilpest** [comment]
This issue is related to ps-dispatch > server > sv.main - related to this function not returning to true, evident when you recreate this with both police/ems, ems is able to respond, but not police.

`local function IsPoliceJob(job) 
    local PoliceJobs = Config.AuthorizedJobs.LEO.Jobs 
    for k, v in pairs(PoliceJobs) do 
        print(job, v) 
        if job == v then 
            return true 
        end 
    end 
    return false 
end`

**Comment by DooubleTap** [comment]
> This issue is related to ps-dispatch > server > sv.main - related to this function not returning to true, evident when you recreate this with both police/ems, ems is able to respond, but not police.
> 
> `local function IsPoliceJob(job) local PoliceJobs = Config.AuthorizedJobs.LEO.Jobs for k, v in pairs(PoliceJobs) do print(job, v) if job == v then return true end end return false end`

could you explain to me like im five, English is not my main language, and i am looking at this file like it's my son and he did something wrong, but i can't guess what to edit.

**Comment by MonkeyWhisper** [comment]
> > This issue is related to ps-dispatch > server > sv.main - related to this function not returning to true, evident when you recreate this with both police/ems, ems is able to respond, but not police.
> > `local function IsPoliceJob(job) local PoliceJobs = Config.AuthorizedJobs.LEO.Jobs for k, v in pairs(PoliceJobs) do print(job, v) if job == v then return true end end return false end`
> 
> could you explain to me like im five, English is not my main language, and i am looking at this file like it's my son and he did something wrong, but i can't guess what to edit.

This is not for support.
