### ISSUE TITLE
Ambulance not able to search for people in report

### ISSUE THREAD

**Issue by TimyStream** [Project-Sloth/ps-mdt#184]
Hi, i installed the MDT, tested it and then found out that the ambulance is not able to search for people to add them to a report.

I also found out why its not working:
This code in line: 654-660
```LUA
RegisterNetEvent('mdt:server:incidentSearchPerson', function(query)
    if query then
		local src = source
		local Player = QBCore.Functions.GetPlayer(src)
		if Player then
			local JobType = GetJobType(Player.PlayerData.job.name)
			if JobType == 'police' or JobType == 'doj' then
```
There is a request that checks which jobs are allowed to search for persons via the incident search ui, but if we now alter the code to look like this:
```LUA
RegisterNetEvent('mdt:server:incidentSearchPerson', function(query)
    if query then
		local src = source
		local Player = QBCore.Functions.GetPlayer(src)
		if Player then
			local JobType = GetJobType(Player.PlayerData.job.name)
			if JobType == 'police' or JobType == 'doj' or JobType == 'ambulance' then
```
we essentially just add the "ambulance" job to the allowed jobs for the request and then its working :)

I hope i can help with this :)

**Comment by MonkeyWhisper** [comment]
Incident, ambulance does not need to have ANY access to that. Not broken.

**Comment by TimyStream** [comment]
> Incident, ambulance does not need to have ANY access to that. Not broken.

Yes thats right. But the problem is that because of the reskin, the ambulance have a reports tab to write reports for them. But they can't add people to the "EMS Involved" section because this uses in the background the above stated Event. This means when they try to search for another paramedic or a doctor they will never be able to find them because the event will never search for it. And above i stated a way how this could be solved. But if you have other ideas i would like to hear them.
