### ISSUE TITLE
VehData Error message. 

### ISSUE THREAD

**Issue by luckygadgetgirl** [Project-Sloth/ps-mdt#192]
Error during NUI callback getProfileData: @ps-mdt/client/main.lua:334: attempt to index a nil value (local 'vehData') Indicates that the vehicle is not in the vehicle.lua in the shared folder. 
![image](https://user-images.githubusercontent.com/1713733/226523042-be4e4a45-6762-46bf-a176-f5eec6f2c19c.png)

**Comment by MonkeyWhisper** [comment]
Thanks for opening this after I asked you, we'll add a print so it tells you why

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/commit/b6dcc48aca322c6ca41ea6df7cb39fa80afbc207
