### ISSUE TITLE
Impound Issue

### ISSUE THREAD

**Issue by skrimxyz** [Project-Sloth/ps-mdt#2]
![image](https://user-images.githubusercontent.com/92062857/161375278-c14352c2-7aa6-4317-97c8-4cb1245bee9e.png)

**Comment by MonkeyWhisper** [comment]
Is this still happening?

**Comment by skrimxyz** [comment]
> Is this still happening?

yes

**Comment by HATE-dev** [comment]
i'm not having that problem

**Comment by pushkart2** [comment]
this is not an issue on my end too. Just so you know, you can use either default qbcore impound or this mdt impound. If you use both, there's a high possibilty, it will bug out!
