### ISSUE TITLE
Profile updates not saving "fingerprint is not defined"

### ISSUE THREAD

**Issue by Gnavling** [Project-Sloth/ps-mdt#210]
Whenever you attempt to make a change on a profile, you'll get this in F8
script:ps-mdt:nui Uncaught ReferenceError: fingerprint is not defined (@ps-mdt/ui/app.js:563)

It appears that there is no way to add a fingerprint.

**Comment by MonkeyWhisper** [comment]
You don't ADD a fingerprint.
