### ISSUE TITLE
DOJ Job Issues - Profile info not populating and not saving edits.

### ISSUE THREAD

**Issue by ikatelynne** [Project-Sloth/ps-mdt#211]
When set as the DOJ job (either lawyer or judge, both produce the same result) the MDT does not pull all of the info for the profiles, and any edits they make are not saved. Attached are the Logs from my f8 console, the txadmin log, and the differences in information that shows up as PD vs DOJ jobs.

![FiveM_b2699_GTAProcess_9qNQ5d3pna](https://user-images.githubusercontent.com/62281767/227377971-78056777-7869-4294-8a86-78b215ff4662.png)
![FiveM_b2699_GTAProcess_kaojkJ6nZ7](https://user-images.githubusercontent.com/62281767/227378137-83c9f6b6-02d8-4f6d-9137-79a6b33f8ac2.png)

[CitizenFX_log_2023-03-23T220750.log](https://github.com/Project-Sloth/ps-mdt/files/11056797/CitizenFX_log_2023-03-23T220750.log)
[fxserver_1679609936.log](https://github.com/Project-Sloth/ps-mdt/files/11056800/fxserver_1679609936.log)

**Comment by MonkeyWhisper** [comment]
DOJ and Laywer never had access to edit the MDT, they were read only

**Comment by ikatelynne** [comment]
After updating to the most recent update version of the script (2.3.1) here's the screenshots and logs for it.


![FiveM_b2699_GTAProcess_zgRJ33SlJm](https://user-images.githubusercontent.com/62281767/227381289-ef8fbe98-09bc-4bb5-bf6c-f99d25cfc10c.png)
![FiveM_b2699_GTAProcess_1sh2Nwe14P](https://user-images.githubusercontent.com/62281767/227381363-c19d849e-0cf3-48b0-98f9-9467ec8c674a.png)

[fxserver_1679611520.log](https://github.com/Project-Sloth/ps-mdt/files/11056965/fxserver_1679611520.log)
[CitizenFX_log_2023-03-23T224135.log](https://github.com/Project-Sloth/ps-mdt/files/11056967/CitizenFX_log_2023-03-23T224135.log)

**Comment by MonkeyWhisper** [comment]
Thank you! So we are missing the user info on there

**Comment by MonkeyWhisper** [comment]
> After updating to the most recent update version of the script (2.3.1) here's the screenshots and logs for it.
> 
> ![FiveM_b2699_GTAProcess_zgRJ33SlJm](https://user-images.githubusercontent.com/62281767/227381289-ef8fbe98-09bc-4bb5-bf6c-f99d25cfc10c.png) ![FiveM_b2699_GTAProcess_1sh2Nwe14P](https://user-images.githubusercontent.com/62281767/227381363-c19d849e-0cf3-48b0-98f9-9467ec8c674a.png)
> 
> [fxserver_1679611520.log](https://github.com/Project-Sloth/ps-mdt/files/11056965/fxserver_1679611520.log) [CitizenFX_log_2023-03-23T224135.log](https://github.com/Project-Sloth/ps-mdt/files/11056967/CitizenFX_log_2023-03-23T224135.log)

Technically, this isn't wrong or broken, it's just how it is. 

Because if a police saves the not, then doj cannot see it and if DOJ saves a notes, police cannot see it.

You can see which notes are saved by the police on your mdt_data database and which were saved by DOJ
