### ISSUE TITLE
Search by Fingerprint

### ISSUE THREAD

**Issue by Magnitrude** [Project-Sloth/ps-mdt#212]
Since MDT was last updated I can no longer search profiles by fingerprint. I would like to suggest adding that feature.

**Comment by LeSiiN** [comment]
Already in the making

**Comment by MonkeyWhisper** [comment]
> Since MDT was last updated I can no longer search profiles by fingerprint. I would like to suggest adding that feature.

Go ahead and make it, send a PR.
