### ISSUE TITLE
Warrants causing error if incident is deleted

### ISSUE THREAD

**Issue by WoWisme** [Project-Sloth/ps-mdt#217]
When you have a warrant from an incident, and that incident gets deleted, it is making errors saying I still have an warrant, which didn't get deleted when deleting a incident case. It makes it bug so you aren't able to view the characters profile. That is caused by it still seeing a warrant, but Title being nil and returning an error..

(The link expires after 1 day, so contact me if you need it reuploaded)
https://streamable.com/4xmxnv

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/compare/716bd3e18d58...f9cb29504fc7
