### ISSUE TITLE
Licenses does not save

### ISSUE THREAD

**Issue by CreelEU** [Project-Sloth/ps-mdt#219]
After recent update, mdt removes the whole "licenses" section from the database, and licenses does not save either.

**Comment by xFutte** [comment]
This is most likely related to the changes in commit 3a571402669dc49253c89aa1fbd1dd5411c4016f.

**Comment by xFutte** [comment]
Looks like the licenses never gets pulled from the profileData:

![image](https://user-images.githubusercontent.com/6727484/227676815-6c137c87-7951-486c-8896-c11fe003dfec.png)

Therefore, the license variable never gets any values into it..
![image](https://user-images.githubusercontent.com/6727484/227677536-ebd7994e-7a18-40d4-8d1c-d55caac1d4a1.png)

.. resulting in the `saveProfile` function in the Lua never receiving the licenses.

![image](https://user-images.githubusercontent.com/6727484/227677788-07f31a42-d1e4-4480-a0b4-8f5f0d171dd0.png)

Callstack leading to error:
![image](https://user-images.githubusercontent.com/6727484/227677825-63c93f54-6a9d-4b68-bf6c-92e85842e09d.png)
![image](https://user-images.githubusercontent.com/6727484/227677891-a6de56ca-fb4d-40f3-ab20-9994e95bea1b.png)
![image](https://user-images.githubusercontent.com/6727484/227678008-e2f9d9d8-3725-478f-8049-da62f0cab457.png)

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/pull/220
