### ISSUE TITLE
mdt won't open 

### ISSUE THREAD

**Issue by ZRswe10** [Project-Sloth/ps-mdt#224]
Can someone help me with my ps-mdt? I have installed the mdt the right way and I have the job and I have everything I need to use it but it doesn't open with just /mdt is their any other way to open it or is their a code that has to be changed?

**Comment by xFutte** [comment]
For all support questions, ask in our [Discord](https://www.discord.gg/projectsloth) support chat. Do not create issues if you need help. Issues are for bug reporting and new features only.
