### ISSUE TITLE
mdt vinscratches

### ISSUE THREAD

**Issue by SirMusk** [Project-Sloth/ps-mdt#225]
make the mdt player vehicles able to when looking at profiles not bring up vinscratches and the search feature not bring up vinscratches with a column of vinscratched played with it for ages and keep getting a error with spinning circle when trying to search for it

**Comment by MonkeyWhisper** [comment]
Yeah, that sounds like a great idea! Send in a PR, we will review it.

**Comment by SirMusk** [comment]
i havent been able to do it im using this as a feature request

**Comment by MonkeyWhisper** [comment]
> i havent been able to do it im using this as a feature request

We are not interested in addressing feature request, I hope you figure it out and get it working on your end
