### ISSUE TITLE
Off Duty

### ISSUE THREAD

**Issue by KrnkTV** [Project-Sloth/ps-mdt#233]
When someone click for off duty this error pop up in server side

[       script:qb-mdt] SCRIPT ERROR: @qb-mdt/server/main.lua:27: attempt to div a 'string' with a 'number'
[       script:qb-mdt] > format_time (@qb-mdt/server/main.lua:27)
[       script:qb-mdt] > handler (@qb-mdt/server/main.lua:201)
[       script:qb-mdt] > <unknown> (@oxmysql/dist/build.js:22252)
[       script:qb-mdt] > runMicrotasks (<anonymous>:0)
[       script:qb-mdt] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by MonkeyWhisper** [comment]
That's not an issue, cannot duplicate. Poor explanation.
