### ISSUE TITLE
utiil.lua5 error

### ISSUE THREAD

**Issue by Dash1003** [Project-Sloth/ps-mdt#257]
hey i have this problem any1 can help me 
![image](https://user-images.githubusercontent.com/92861810/229182455-380ee29b-dc55-4359-9970-18db6ad41530.png)

**Comment by xFutte** [comment]
Ask for help in Discord.

**Comment by Dash1003** [comment]
i have a pm =)

**Comment by d-w00d** [comment]
Did you figure this out? I am to seeing this

**Comment by Dash1003** [comment]
unfortunately I still have the error
