### ISSUE TITLE
util.lua no fix pls help

### ISSUE THREAD

**Issue by Dash1003** [Project-Sloth/ps-mdt#258]
hey i need any1 for this fix
![image](https://user-images.githubusercontent.com/92861810/229205673-0f7d5a1e-de8c-455d-a153-655bf0f58496.png)

**Comment by MonkeyWhisper** [comment]
Stop opening issues for support. Either fix it yourself or ask in Discord.

**Comment by Dash1003** [comment]
you banned me in the discord because i asked a supporter for help

**Comment by MonkeyWhisper** [comment]
I banned you from Discord because you pinged and DM staff members for support. Now you're out of luck.

Figure it out.

**Comment by Dash1003** [comment]
Yes, I'm sorry, I misunderstood that I should write to the one gentleman in the discord
