### ISSUE TITLE
BCSO or players marked under sheriffs office doesn’t show up normally in MDT

### ISSUE THREAD

**Issue by ckaysone380** [Project-Sloth/ps-mdt#26]
So my QB police job is configured to have both Police and Sheriff under one job and I am having problems with getting the Guys who are BCSO to show up on the MDT for where has how many are on duty, I went in to the client and server Lua to add in sheriff and anyone under the Sheriff job only shows up as unknown But I have it now where they are able to access the MDT but when they are on the roster they are unknown

**Comment by pushkart2** [comment]
BCSO is not the base job for QBCore, you can edit the mdt files to make those compatible with custom jobs you add.
