### ISSUE TITLE
[SUGGESTION] Remove auto-populating fingerprint information

### ISSUE THREAD

**Issue by nggcasey** [Project-Sloth/ps-mdt#262]
Police in real life don't automatically have everyone's fingerprints, they only have them if someone has been arrested before. Police should have to verify the person's identity by asking them questions (i.e. what vehicles they own, what previous police involvements they've had etc), and then manually enter their fingerprint to their profile for it to be saved.

This is how the MDT used to work but now it auto-populates.

**Comment by MonkeyWhisper** [comment]
Go ahead and read the code, you will see MDT fingerprints ONLY gets added if the person has more than 1 CONVICTION. Meaning, they have already been booked and processed. 


> Police in real life don't automatically have everyone's fingerprints, they only have them if someone has been arrested before. Police should have to verify the person's identity by asking them questions (i.e. what vehicles they own, what previous police involvements they've had etc), and then manually enter their fingerprint to their profile for it to be saved.
> 
> This is how the MDT used to work but now it auto-populates.
