### ISSUE TITLE
Resolution Issues?

### ISSUE THREAD

**Issue by nzkfc** [Project-Sloth/ps-mdt#274]
Some of our cops were saying property isn't showing up, on checking I can re-create the issue myself based on resolution

Example of the MDT running on a 42" monitor:
![image](https://user-images.githubusercontent.com/5011997/230706189-157b265b-05a0-4976-b7b1-26b9806b14b4.png)

Then running on smaller resolutions (not exactly sure on the size, below 27" 1440p though:
![image](https://user-images.githubusercontent.com/5011997/230706218-56de560c-8cda-4f3d-9928-c12cbb0c3e74.png)

Then larger again but not quite 42":
https://i.imgur.com/eSk961C.png

**Comment by nzkfc** [comment]
Actually what might work better for the MDT dashboard is to make the categories like "Licenses" and "Vehicles" be just collapsible headers so you can close/open them to give more room on the screen. Or maybe even headers along the top that work like browser tabs.

**Comment by LeSiiN** [comment]
Could u tell me ur version ? Looks like from months ago

**Comment by nzkfc** [comment]
Yeah 1.6 actually, I didn't set up this script but thats a doozzzy, i'll get whoever did it to re-do it with latest smh

**Comment by LeSiiN** [comment]
Yeah newest is 2.3.7 i think, so update ur mdt <3
