### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by Xandrice** [Project-Sloth/ps-mdt#276]
If you ever had the police job at any point on your character, it still logs to the webhook. 

![image](https://user-images.githubusercontent.com/48589989/230717994-18cdc2f2-8579-4887-ac75-8807045a1881.png)

**Comment by MonkeyWhisper** [comment]
This only happens if you clockin and out via ps-mdt only

**Comment by Xandrice** [comment]
I didn't clock out on the MDT, I f8 quit.

**Comment by Goykz** [comment]
Same issue and play times are wrong aswell showing 22hrs of play time only hired on a day ago
