### ISSUE TITLE
BUG - Search profile licenses don't reflect the profile's licenses

### ISSUE THREAD

**Issue by Veolene** [Project-Sloth/ps-mdt#290]
Hello,

It seems that when searching for the user the licenses does not update based on the profile's licenses, see the image below

![image](https://user-images.githubusercontent.com/53438206/231893125-6b118018-bf5c-4c0e-ab49-1c76bdfd1ebf.png)

In the search section on the left, there are a couple of licenses visible and they are all marked red. On the profile itself, the profile has a drivers license, but that doesn't reflect when searching for the profile in the search section.

**Comment by YungT-SevsideRP** [comment]
having the same problem

**Comment by Veolene** [comment]
Still an issue with the new update

**Comment by MonkeyWhisper** [comment]
> Still an issue with the new update

Then fix it

**Comment by Veolene** [comment]
> > Still an issue with the new update
> 
> Then fix it

Then don't mark it as completed but as ongoing

**Comment by MonkeyWhisper** [comment]
> > > Still an issue with the new update
> > 
> > 
> > Then fix it
> 
> Then don't mark it as completed but as ongoing

Then you fix it if you want it completed.
