### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MartinMarih** [Project-Sloth/ps-mdt#293]
I have follow every step by step and I'm getting this and I don't understand what is suppose to show up when you want to register a weapon to the police side. cause at the moment it don't show un anything in de MDT
![Screenshot 2023-04-18 214946](https://user-images.githubusercontent.com/61891359/232969924-8e5d2a28-43a0-419c-a24f-19fc6246d702.png)

**Comment by xFutte** [comment]
This is a database problem on your end. Set it up as it should be.
