### ISSUE TITLE
EMS MDT - Entering patient name should use the same search box as the other fields

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#304]
When you go to create an ICU report it asks you to enter the persons name and CID. It does not give you the expected format. This is a bit confusing and can lead to simple errors. 

![image](https://user-images.githubusercontent.com/18689469/233872987-5e745cb0-6628-44fc-a0a1-668c8affa831.png)

Instead we should use the same profile picker that the EMS involved section and other "people pickers" use in the police version of the MDT.

Additionally the save functionality appears to be broken when trying to save an ICU report.
I have all the information filled out, but the report never saves. NO errors on client or server
![image](https://user-images.githubusercontent.com/18689469/233873078-c14237d5-f190-402f-bf4c-c9076343f057.png)
I noticed that we are trying to save EMS reports under the mdt-bolos table tho, which sorta seems like the wrong place to save these??

**Comment by MonkeyWhisper** [comment]
Closed, we will get this corrected on v2 as the whole thing is being remade
