### ISSUE TITLE
Add ability to search by fingerprint

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#305]
Currently if you search by fingerprint it will return no results
![image](https://user-images.githubusercontent.com/18689469/233873244-6d4d72c8-0ac6-49e7-9b74-5f0c5507453b.png)

![image](https://user-images.githubusercontent.com/18689469/233873256-6e2c5c41-788a-4dde-8bd0-a073964f71e4.png)

We should add fingerprint as an additional search field

**Comment by MonkeyWhisper** [comment]
I see what the issue is, the fingerprint is not getting saved to the database after being convicted so when you try searching for it, nothing comes up, but if you manually add it to the database and try searching for it, it works

![image](https://user-images.githubusercontent.com/82112471/233889942-8192ebaa-df16-4cda-a9d3-fd8316b8fec2.png)

**Comment by BackSH00TER** [comment]
Which database are we searching for it in? I think we should be able to search for it in the `players` DB table, under metadata. 
Tho since its json encoded json blob, it might not be efficient to decode/unpack and search it. 

I think I had seen fingerprint was added to one of the tables ps- tables tho as well? Maybe for that reason, so its easier to index on?

**Comment by MonkeyWhisper** [comment]
I'm reverting it back, so that it saves to the databae and cops needs to manually enter fingerprints again rather than auto populating them... sounds a lot like power gaming even though it's convenient

**Comment by MonkeyWhisper** [comment]
> Currently if you search by fingerprint it will return no results ![image](https://user-images.githubusercontent.com/18689469/233873244-6d4d72c8-0ac6-49e7-9b74-5f0c5507453b.png)
> 
> ![image](https://user-images.githubusercontent.com/18689469/233873256-6e2c5c41-788a-4dde-8bd0-a073964f71e4.png)
> 
> We should add fingerprint as an additional search field

https://github.com/Project-Sloth/ps-mdt/pull/312
