### ISSUE TITLE
Person search does not allow search by FirstName + LastName

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#306]
If you search by first and last name you will get no results, you have to search by either one
![image](https://user-images.githubusercontent.com/18689469/233873358-499eeaa9-a34d-45a0-9fbe-7b5dc5d44f1a.png)

![image](https://user-images.githubusercontent.com/18689469/233873363-1982659c-9939-4b2f-9a18-253e582e6db2.png)
![image](https://user-images.githubusercontent.com/18689469/233873367-92a69275-a37d-49a1-a071-0fab05747cf0.png)

Profiles search appears to support search by first and last, so we just need to borrow the logic from there
![image](https://user-images.githubusercontent.com/18689469/233873397-b1329518-8697-4eb9-b7bd-3c304ab1adf7.png)

**Comment by BackSH00TER** [comment]
Reference line we use for searchProfiles
`local people = MySQL.query.await("SELECT p.citizenid, p.charinfo, md.pfp FROM players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(CONCAT(JSON_VALUE(p.charinfo, '$.firstname'), ' ', JSON_VALUE(p.charinfo, '$.lastname'))) LIKE :query OR LOWER(`charinfo`) LIKE :query OR LOWER(`citizenid`) LIKE :query AND jobtype = :jobtype LIMIT 20", { query = string.lower('%'..sentData..'%'), jobtype = JobType })`

**Comment by MonkeyWhisper** [comment]
> If you search by first and last name you will get no results, you have to search by either one ![image](https://user-images.githubusercontent.com/18689469/233873358-499eeaa9-a34d-45a0-9fbe-7b5dc5d44f1a.png)
> 
> ![image](https://user-images.githubusercontent.com/18689469/233873363-1982659c-9939-4b2f-9a18-253e582e6db2.png) ![image](https://user-images.githubusercontent.com/18689469/233873367-92a69275-a37d-49a1-a071-0fab05747cf0.png)
> 
> Profiles search appears to support search by first and last, so we just need to borrow the logic from there ![image](https://user-images.githubusercontent.com/18689469/233873397-b1329518-8697-4eb9-b7bd-3c304ab1adf7.png)

I can search by last name, check this out 

https://gyazo.com/31f2a1da0f994cb993bf0e5516dc90dd

**Comment by BackSH00TER** [comment]
@MonkeyWhisper The bug is that if you type FirstName LastName the results will not show. 
You can only search if you put ONLY First OR Last. Combined does not work.

**Comment by MonkeyWhisper** [comment]
> @MonkeyWhisper The bug is that if you type FirstName LastName the results will not show. You can only search if you put ONLY First OR Last. Combined does not work.

Ops! Sorry, okay, yup, I was able to duplicate it

Searching for both first AND last name, no results

**Comment by MonkeyWhisper** [comment]
> @MonkeyWhisper The bug is that if you type FirstName LastName the results will not show. You can only search if you put ONLY First OR Last. Combined does not work.

https://gyazo.com/945ee100267fedf00fdc3bbcf2c79313

Check it out :)

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/pull/317
