### ISSUE TITLE
Staff logs -LogPerms have to be declared for each rank rather than applied to all ranks above it

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#308]
The logperms are currently setup such that you have to specify for each rank a true/false of whether that rank can access the logs.

It should be that you just put the minimum rank per job that is required to view the logs. For example if I put grade `4` for police, then any grade above should also get the perms.

**Comment by LeSiiN** [comment]
In my opinion its good how it is, so when someone got a first responder role that doesnt need staff logs perms but its above 4 then he can disable it

**Comment by MonkeyWhisper** [comment]
> 

I can see why this is a good logic for it but for example, Rookies that's ranked 1 as LSPD but if I set rank 4 being LT and above then that means rookie will also have access to it 

We should leave it as is
