### ISSUE TITLE
Ability to add multiple photos to the DMV Vehicle Information screen

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#309]
It would be nice to have the ability to upload multiple photos for a vehicle. We could just add the gallery section like we have in several other areas.
![image](https://user-images.githubusercontent.com/18689469/233920013-a1e1778a-360e-40f5-83c8-117150a33849.png)

**Comment by RatulKoley** [comment]
+1

**Comment by MonkeyWhisper** [comment]
Closed, we will get this corrected on v2 as the whole thing is being remade
