### ISSUE TITLE
QB-Inventory

### ISSUE THREAD

**Issue by dontaythedon** [Project-Sloth/ps-mdt#310]
I'm in a learning curve to figure out how to properly import code into events. I've been having issues with the the QB-Inventory and making it with 

*RegisterNetEvent('inventory:server:SetInventoryData', function(fromInventory, toInventory, fromSlot, toSlot, fromAmount, toAmount)*

Please help

**Comment by xFutte** [comment]
Get help in the Discord for Project Sloth.
