### ISSUE TITLE
Issues with Photos and the dashboard dispatch

### ISSUE THREAD

**Issue by Xandrice** [Project-Sloth/ps-mdt#32]
On the Police MDT, I saved a photo of an individual, when I view it on the EMS side, it shows it in the search, but not in the profile when I click it. See examples below. 

![FiveM_b2372_GTAProcess_KOMVawNw9i](https://user-images.githubusercontent.com/48589989/165461761-e3c2549b-e997-4586-a56d-8cf82ab5abdf.png)
![FiveM_b2372_GTAProcess_4jAJW8UQml](https://user-images.githubusercontent.com/48589989/165461820-210e5b44-d7b8-411c-885d-f9cbfe215d10.png)

The Licenses, vehicles, properties don't also load when you select the individual. 
 
When you are on duty as EMS, and you look at the police officers in your active units, it shows you all the officers that have been on duty and they never go away when they go off duty. It also shows EMS as LSPD, and PD as unknown for EMS. 
![image](https://user-images.githubusercontent.com/48589989/165461059-6908b798-a701-48f8-bc33-cac0d63ee73c.png)

**Comment by trapw0w** [comment]
>  It also shows EMS as LSPD, and PD as unknown for EMS.

Ensure you're using the latest version, this has been fixed.

As for your other issue with off-duty showing up, this is due to the fact that `activeUnits` is never updated server side during a duty toggle, `onPlayerDropped` or even on `QBCore:Client:OnPlayerUnload`. I have made changes in my local branch to fix this via:

- Modify client to listen for `QBCore:Client:OnPlayerUnload` and trigger server event.
```lua
--// client/main.lua
RegisterNetEvent('QBCore:Client:OnPlayerUnload', function()
    TriggerServerEvent("qb-mdt:server:OnPlayerUnload")
end)

RegisterNetEvent('mdt:client:open', function(bulletin, activeUnits, cid)
    EnableGUI(true)
    local x, y, z = table.unpack(GetEntityCoords(PlayerPedId()))

    local currentStreetHash, intersectStreetHash = GetStreetNameAtCoord(x, y, z)
    local currentStreetName = GetStreetNameFromHashKey(currentStreetHash)
    local intersectStreetName = GetStreetNameFromHashKey(intersectStreetHash)
    local zone = tostring(GetNameOfZone(x, y, z))
    local area = GetLabelText(zone)
    local playerStreetsLocation = area

    if not zone then zone = "UNKNOWN" end;

    if intersectStreetName ~= nil and intersectStreetName ~= "" then playerStreetsLocation = currentStreetName .. ", " .. intersectStreetName .. ", " .. area
    elseif currentStreetName ~= nil and currentStreetName ~= "" then playerStreetsLocation = currentStreetName .. ", " .. area
    else playerStreetsLocation = area end

    --// Change here to pass config option to only show on duty units and the local players citizenid
    SendNUIMessage({ type = "data", activeUnits = activeUnits, citizenid = cid, ondutyonly = Config.OnlyShowOnDuty, name = "Welcome, " ..PlayerData.job.grade.name..' '..PlayerData.charinfo.lastname:sub(1,1):upper()..PlayerData.charinfo.lastname:sub(2), location = playerStreetsLocation, fullname = PlayerData.charinfo.firstname..' '..PlayerData.charinfo.lastname, bulletin = bulletin })
    TriggerEvent("mdt:client:dashboardWarrants")
end)
```

- Listen server side for client originated calls and `onPlayerDropped`. Remove user from the active units when they toggle duty to off.
```lua
--// server/main.lua

RegisterServerEvent("playerDropped")
AddEventHandler("playerDropped", function(reason)
	--// Delete player from the MDT on logout
	local src = source
	local player = QBCore.Functions.GetPlayer(src)
	if activeUnits[player.PlayerData.citizenid] ~= nil then
		activeUnits[player.PlayerData.citizenid] = nil
	end
end)

RegisterNetEvent("qb-mdt:server:OnPlayerUnload", function()
	--// Delete player from the MDT on logout
    local src = source
    local player = QBCore.Functions.GetPlayer(src)
    if activeUnits[player.PlayerData.citizenid] ~= nil then
        activeUnits[player.PlayerData.citizenid] = nil
    end
end)

RegisterNetEvent("qb-mdt:server:ToggleDuty", function()
    local src = source
    local player = QBCore.Functions.GetPlayer(src)
	if not player.PlayerData.job.onduty then
		--// Remove from MDT
		if activeUnits[player.PlayerData.citizenid] ~= nil then
			activeUnits[player.PlayerData.citizenid] = nil
		end
	end
end)

RegisterNetEvent('mdt:server:openMDT', function()
	local src = source
	local PlayerData = GetPlayerData(src)
	if not PermCheck(src, PlayerData) then return end
	local Radio = Player(src).state.radioChannel or 0

	activeUnits[PlayerData.citizenid] = {
		cid = PlayerData.citizenid,
		callSign = PlayerData.metadata['callsign'],
		firstName = PlayerData.charinfo.firstname:sub(1,1):upper()..PlayerData.charinfo.firstname:sub(2),
		lastName = PlayerData.charinfo.lastname:sub(1,1):upper()..PlayerData.charinfo.lastname:sub(2),
		radio = Radio,
		unitType = PlayerData.job.name,
		duty = PlayerData.job.onduty
	}

	local JobType = GetJobType(PlayerData.job.name)
	local bulletin = GetBulletins(JobType)
	
	--// Modify client event here to pass PlayerData.citizenid of the local player
	TriggerClientEvent('mdt:client:open', src, bulletin, activeUnits, PlayerData.citizenid)
end)
```

- Modify MDT UI to only display on duty units + the local client if they're off duty
```js
  let activeUnits = eventData.activeUnits;
  let cid = eventData.citizenid;
  let onDutyOnly = eventData.ondutyonly;
  $(".active-unit-list").html(' ');
  let unitListHTML = '';

  activeUnits = Object.values(activeUnits)
  activeUnits.forEach((unit) => {
	if (onDutyOnly && unit.duty == 0 && unit.cid != cid) {
	  return
	}
	let status = unit.duty == 1 ? "10-8" : '10-7';
	let statusColor = unit.duty == 1 ? "green-status" : 'yellow-status';
	let radioBack = unit.sig100 ? "#7b2c2c" : "var(--color-3)";
	let radio = unit.radio ? unit.radio : "0";
	let callSign = unit.callSign ? unit.callSign : "000";
	let activeInfoJob = `<div class="unit-job active-info-job-unk">UNKNOWN</div>`;
	if (PoliceJobs[unit.unitType] !== undefined) {
	  policeCount++;
	  activeInfoJob = `<div class="unit-job active-info-job-lspd">LSPD</div>`;
	} else if (AmbulanceJobs[unit.unitType] !== undefined) {
	  activeInfoJob = `<div class="unit-job active-info-job-ambulance">Ambulance</div>`
	  emsCount++;
	} else if (DojJobs[unit.unitType] !== undefined) {
	  activeInfoJob = `<div class="unit-job active-info-job-doj">DOJ</div>`
	  dojCount++;
	} else if (FireJobs[unit.unitType] !== undefined) {
	  activeInfoJob = `<div class="unit-job active-info-job-doj">Fire Dept</div>`
	  fireCount++;
	}

	unitListHTML += `
				<div class="active-unit-item" data-id="${unit.cid}">
					<div class="unit-status ${statusColor}">${status}</div>
					${activeInfoJob}
					<div class="unit-name">(${callSign}) ${unit.firstName} ${unit.lastName}</div>
					<div class="unit-radio" style="background-color: ${radioBack};">${radio}</div>
				</div>
			`;
  });
```

**Comment by trapw0w** [comment]
Vehicles are only rendered if you're in the police job:

https://github.com/Project-Sloth/qb-mdt/blob/main/server/main.lua#L185-L230

In reality, do you really want people in the ambulance job seeing a players vehicles? imo we should be hiding that HTML element for any job apart from Police.

**Comment by trapw0w** [comment]
Finally, the Profile Pictures, you can see here that `JobType` is passed into essentially a DB callback to get the profile data:

https://github.com/Project-Sloth/qb-mdt/blob/main/server/main.lua#L232

Which is then used in this DB query, note that you can see here the query results are being filtered by `jobtype`, meaning that each job can essentially store a different record in the DB for the character. In reality, I think we could probably remove the jobtype filter

https://github.com/Project-Sloth/qb-mdt/blob/main/server/dbm.lua#L25-L29

**Comment by HATE-dev** [comment]
> Finally, the Profile Pictures, you can see here that `JobType` is passed into essentially a DB callback to get the profile data:
> 
> https://github.com/Project-Sloth/qb-mdt/blob/main/server/main.lua#L232
> 
> Which is then used in this DB query, note that you can see here the query results are being filtered by `jobtype`, meaning that each job can essentially store a different record in the DB for the character. In reality, I think we could probably remove the jobtype filter
> 
> https://github.com/Project-Sloth/qb-mdt/blob/main/server/dbm.lua#L25-L29

is this normal?
![image](https://user-images.githubusercontent.com/78761393/165518852-8a705437-6c60-40bf-818a-634b2dfd192a.png)

**Comment by trapw0w** [comment]
> > Finally, the Profile Pictures, you can see here that `JobType` is passed into essentially a DB callback to get the profile data:
> > https://github.com/Project-Sloth/qb-mdt/blob/main/server/main.lua#L232
> > Which is then used in this DB query, note that you can see here the query results are being filtered by `jobtype`, meaning that each job can essentially store a different record in the DB for the character. In reality, I think we could probably remove the jobtype filter
> > https://github.com/Project-Sloth/qb-mdt/blob/main/server/dbm.lua#L25-L29
> 
> is this normal? ![image](https://user-images.githubusercontent.com/78761393/165518852-8a705437-6c60-40bf-818a-634b2dfd192a.png)

Can you show me your `server/main.lua`, specifically the function/event handler in which line 33 sits

**Comment by HATE-dev** [comment]
> > > Finally, the Profile Pictures, you can see here that `JobType` is passed into essentially a DB callback to get the profile data:
> > > https://github.com/Project-Sloth/qb-mdt/blob/main/server/main.lua#L232
> > > Which is then used in this DB query, note that you can see here the query results are being filtered by `jobtype`, meaning that each job can essentially store a different record in the DB for the character. In reality, I think we could probably remove the jobtype filter
> > > https://github.com/Project-Sloth/qb-mdt/blob/main/server/dbm.lua#L25-L29
> > 
> > 
> > is this normal? ![image](https://user-images.githubusercontent.com/78761393/165518852-8a705437-6c60-40bf-818a-634b2dfd192a.png)
> 
> Can you show me your `server/main.lua`, specifically the function/event handler in which line 33 sits

![image](https://user-images.githubusercontent.com/78761393/165726765-4ae31eac-6b7e-44fb-8358-a03469aaa884.png)

**Comment by trapw0w** [comment]
@HATE-dev How did you disconnect from the server? I just tested using this exact code:

```lua
RegisterServerEvent("playerDropped")
AddEventHandler("playerDropped", function(reason)
	--// Delete player from the MDT on logout
	print("player dropped!")
	local src = source
	local player = QBCore.Functions.GetPlayer(src)
	if player ~= nil then
		print("Player CID: "..player.PlayerData.citizenid)
	else
		print("Unable to get QBCore Player Handle")
	end
	if activeUnits[player.PlayerData.citizenid] ~= nil then
		activeUnits[player.PlayerData.citizenid] = nil
	end
end)
```

When typing `quit` into the F8 console, I can see here on the server console that I was able to obtain the player handle:
```
[       script:qb-mdt] player dropped!
[       script:qb-mdt] Player CID: IDP42569
```

**Comment by HATE-dev** [comment]
> @HATE-dev How did you disconnect from the server? I just tested using this exact code:
> 
> ```lua
> RegisterServerEvent("playerDropped")
> AddEventHandler("playerDropped", function(reason)
> 	--// Delete player from the MDT on logout
> 	print("player dropped!")
> 	local src = source
> 	local player = QBCore.Functions.GetPlayer(src)
> 	if player ~= nil then
> 		print("Player CID: "..player.PlayerData.citizenid)
> 	else
> 		print("Unable to get QBCore Player Handle")
> 	end
> 	if activeUnits[player.PlayerData.citizenid] ~= nil then
> 		activeUnits[player.PlayerData.citizenid] = nil
> 	end
> end)
> ```
> 
> When typing `quit` into the F8 console, I can see here on the server console that I was able to obtain the player handle:
> 
> ```
> [       script:qb-mdt] player dropped!
> [       script:qb-mdt] Player CID: IDP42569
> ```

its just not me everytime when officer logs off the server its showing up

**Comment by trapw0w** [comment]
> its just not me everytime when officer logs off the server its showing up

I just need to know how the user is exiting the server so I can replicate it. As above, I cannot replicate this issue. 

From what you've shared, the server is unable to get the QB Core player handle for the dropped player. If this is the case and I can eventually reproduce it, we're probably going to have to do a DB callback to get citizen IDs based on a players FiveM license.

**Comment by HATE-dev** [comment]
> > its just not me everytime when officer logs off the server its showing up
> 
> I just need to know how the user is exiting the server so I can replicate it. As above, I cannot replicate this issue.
> 
> From what you've shared, the server is unable to get the QB Core player handle for the dropped player. If this is the case and I can eventually reproduce it, we're probably going to have to do a DB callback to get citizen IDs based on a players FiveM license.

im mostly using f8 quit and sometimes alt f4 but results are same.

**Comment by trapw0w** [comment]
> im mostly using f8 quit and sometimes alt f4 but results are same.

Can you copy and paste the one I used for testing in and show me the results?

**Comment by HATE-dev** [comment]
> > im mostly using f8 quit and sometimes alt f4 but results are same.
> > Can you copy and paste the one I used for testing in and show me the results?

I'm backing up my files rn i'll try it when its done.

**Comment by HATE-dev** [comment]
![image](https://user-images.githubusercontent.com/78761393/165772220-9d3479a2-cc46-46c2-bb0a-bee2c91fb9c4.png)

**Comment by HATE-dev** [comment]
> > im mostly using f8 quit and sometimes alt f4 but results are same.
> 
> Can you copy and paste the one I used for testing in and show me the results?

**Comment by JoeSzymkowiczFiveM** [comment]
> > its just not me everytime when officer logs off the server its showing up
> 
> I just need to know how the user is exiting the server so I can replicate it. As above, I cannot replicate this issue.
> 
> From what you've shared, the server is unable to get the QB Core player handle for the dropped player. If this is the case and I can eventually reproduce it, we're probably going to have to do a DB callback to get citizen IDs based on a players FiveM license.

You planning on pushing a PR for your fixes?

**Comment by JoeSzymkowiczFiveM** [comment]
Profile picture issue should be fixed in latest push.

**Comment by trapw0w** [comment]
> You planning on pushing a PR for your fixes?

One of the issues described in here has to do with vehicles in the Ambulance MDT, which is still awaiting guidance of if this should even show under anywhere apart from the Police MDT.

Only outstanding one is the off duty people showing in the MDT, which I can work on a PR for. Will need to test a callback to get information from the DB.

**Comment by MonkeyWhisper** [comment]
All Gucci! That PR was merged. 

Thanks for the contribution @trapw0w.
