### ISSUE TITLE
Editing BOLO's

### ISSUE THREAD

**Issue by Xandrice** [Project-Sloth/ps-mdt#34]
When I try to edit a BOLO, I get a server error:
`[       script:qb-mdt] SCRIPT ERROR: @oxmysql/lib/MySQL.lua:84: unable to index MySQL.async.execute, expected .await`

**Comment by JoeSzymkowiczFiveM** [comment]
Cannot recreate. Suggest updating to latest version of oxmysql.

**Comment by JoeSzymkowiczFiveM** [comment]
Fixed in #48
