### ISSUE TITLE
/911

### ISSUE THREAD

**Issue by TankinTom** [Project-Sloth/ps-mdt#348]
When doing the /911 Command, I get the following. This is after a 100% fresh install of PS-MDT and PS-Dispatch
![20230531142146_1](https://github.com/Project-Sloth/ps-mdt/assets/90729413/0076dc1d-b47a-4d4c-8713-3fae11ac2c27)

**Comment by TankinTom** [comment]
So how is this fixed then?

**Comment by LeSiiN** [comment]
Its a U problem not a US problem , more questions? ask in the support
[CLICK ME](https://youtu.be/8AYiKJX9u0g)
