### ISSUE TITLE
Translations to NUI

### ISSUE THREAD

**Issue by grzyk** [Project-Sloth/ps-mdt#353]
Hi good thing would be translations to html and js files. More than once we've been faced with the thought of whether it's worth doing an update due to the sheer number of things to translate and we've usually delayed it. Thanks to translations it would be possible to update the script very quickly and it would give a path to multilingualism.

It could work on the principle of separate files such as lang.js 
```
let Translation = {
     players = {
        example = 'example',
     },
}
```
For the js File and for static Translations in html, e.g. 
```$('.playerButton').text('example')```

**Comment by MonkeyWhisper** [comment]
Great, do it and send a PR
