### ISSUE TITLE
Loading after trying to search up a name or vehicle 

### ISSUE THREAD

**Issue by muskettt** [Project-Sloth/ps-mdt#355]
If I try and search up a name or vehicle it loads and does not stop 
![image](https://github.com/Project-Sloth/ps-mdt/assets/136931975/be4d748d-fab2-44e7-a5e5-f219ab64108f)

And it is giving me this error but I did nothing for it to happened. I do not know how to fix it
![image](https://github.com/Project-Sloth/ps-mdt/assets/136931975/b9300c5d-0b4f-4fda-bd8a-dd0a2f0b347d)

**Comment by xFutte** [comment]
Ask for support in Discord.
