### ISSUE TITLE
Bolos or report deleted?

### ISSUE THREAD

**Issue by amgmacht** [Project-Sloth/ps-mdt#36]
find a way to delete bolos or reports maybe with right click or something?

**Comment by QBLes** [comment]
why was this closed?

**Comment by JoeSzymkowiczFiveM** [comment]
Enhancement requests are not issues. Please make suggestions for changes in the discord.

**Comment by QBLes** [comment]
i guess it would be classed as an Enhancement, but i would of thought it would be there from the begining considering need to wipe something in the database if someone messes it up...

Keep up the great work!
