### ISSUE TITLE
Fingerprint doesn't appear automatically

### ISSUE THREAD

**Issue by CKRACER** [Project-Sloth/ps-mdt#373]
The Fingerprint of the player, doesn't appear in hes profile of the police mdt, unless a police officer adds it
![imagem_2023-08-04_155629628](https://github.com/Project-Sloth/ps-mdt/assets/91023530/a0a32351-97de-4229-9660-3fdeed3848a4)

**Comment by LeSiiN** [comment]
because u should add it yourself!
