### ISSUE TITLE
No issue, just a question, to check possibility

### ISSUE THREAD

**Issue by Maureks** [Project-Sloth/ps-mdt#38]
Would it be possible  to add an item to only be able to open the mdt ? 
Example: Police/Ambulance having an item like tablet in their inventory, to be able to use the mdt

What do I need to do ? 
Thanks in advance !

PS- Awesome release, thanks guys !

**Comment by MonkeyWhisper** [comment]
You can add it yourself and make a PR for it. You can use hasitem check.
