### ISSUE TITLE
No export LoadInventory

### ISSUE THREAD

**Issue by TETRA-LLC** [Project-Sloth/ps-mdt#388]
![E5B6D5AB-676D-44C7-B0A3-87D90810BE06](https://github.com/Project-Sloth/ps-mdt/assets/145864412/1aace412-7540-4d59-ac44-3d228068e636)

keep receiving this code, and I know 100% it’s related to ps-mdt. How do I fix this #

**Comment by TETRA-LLC** [comment]
Error* not code

**Comment by lenzh** [comment]
Error is from multicharacters
