### ISSUE TITLE
EMS Profile Errors

### ISSUE THREAD

**Issue by JoMichelle** [Project-Sloth/ps-mdt#39]
Just a fyi, i'm getting this error when trying to look at a profile on the EMS side.
Press profiles, search a name, list pops up, click name,..nothing happens. get the error below in txadmin, no f8 errors.

I have the newest mdt from 15 hours ago.

not sure if its a bug or compatibility issue or whatever, just wanted to let ya know, in case it is a bug. :)

![Snipaste_2022-05-05_02-50-25](https://user-images.githubusercontent.com/46945365/166900898-21c36ae4-748b-4430-98f5-c42e6d4292a3.png)

**Comment by MonkeyWhisper** [comment]
Cannot duplicate issue, works just fine on my end with no errors. 
![image](https://user-images.githubusercontent.com/82112471/167542970-7b0f4e36-94b8-4a92-8e8e-8d4d60b0ac6f.png)
