### ISSUE TITLE
Cant view peoples profile

### ISSUE THREAD

**Issue by RandomDudeontw1tch** [Project-Sloth/ps-mdt#390]
Sometimes it dosent let me open peoples profile and even when it lets me it just stays on that person profile there is nothing in the f8 but here is the tx console 

[      script:qb-core] [qb-core:LOG] RandomDude PLAYER SAVED!
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:1943: ps-mdt was unable to execute a query!
[      script:qb-core] Query: SELECT * FROM properties WHERE owner_citizenid = ?
[      script:qb-core] ["VBU46964"]
[      script:qb-core] Table 'qbcoreframework_109f67.properties' doesn't exist
[      script:qb-core] > GetPlayerPropertiesByCitizenId (@ps-mdt/server/main.lua:1943)
[      script:qb-core] > ref (@ps-mdt/server/main.lua:345)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:371)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:1943: ps-mdt was unable to execute a query!
[      script:qb-core] Query: SELECT * FROM properties WHERE owner_citizenid = ?
[      script:qb-core] ["ZBS21941"]
[      script:qb-core] Table 'qbcoreframework_109f67.properties' doesn't exist
[      script:qb-core] > GetPlayerPropertiesByCitizenId (@ps-mdt/server/main.lua:1943)
[      script:qb-core] > ref (@ps-mdt/server/main.lua:345)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:371)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:1943: ps-mdt was unable to execute a query!
[      script:qb-core] Query: SELECT * FROM properties WHERE owner_citizenid = ?
[      script:qb-core] ["VBU46964"]
[      script:qb-core] Table 'qbcoreframework_109f67.properties' doesn't exist
[      script:qb-core] > GetPlayerPropertiesByCitizenId (@ps-mdt/server/main.lua:1943)
[      script:qb-core] > ref (@ps-mdt/server/main.lua:345)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:371)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:1943: ps-mdt was unable to execute a query!
[      script:qb-core] Query: SELECT * FROM properties WHERE owner_citizenid = ?
[      script:qb-core] ["VBU46964"]
[      script:qb-core] Table 'qbcoreframework_109f67.properties' doesn't exist
[      script:qb-core] > GetPlayerPropertiesByCitizenId (@ps-mdt/server/main.lua:1943)
[      script:qb-core] > ref (@ps-mdt/server/main.lua:345)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:371)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24882)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25056)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Vasil0601** [comment]
I have the same issue, but in my F8 no error is showing up.

**Comment by xFutte** [comment]
Check the error message. I directly says what your issue is.

**Comment by Vasil0601** [comment]
No error message is popping up when I try to open it.
