### ISSUE TITLE
Unable to pull profiles

### ISSUE THREAD

**Issue by TankinTom** [Project-Sloth/ps-mdt#395]
When doing a search fo the profiles, everything comes u[, but when clicking on the profile, this error gets brought back in the console. the SQL was already ran, but I have no idea what this error is in reference to. When I try to join the discord, it says unable to accept the invite.
https://i.imgur.com/wywroRz.png

**Comment by TankinTom** [comment]
![opera_4mI8QrT2Mk](https://github.com/Project-Sloth/ps-mdt/assets/90729413/ac27f99a-29b3-4061-a593-0e3f3b89c354)

**Comment by TankinTom** [comment]
server/main.lua 1943 is referencing the below, which I believe is talking about peoples houses/properties

    local result = MySQL.Sync.fetchAll("SELECT * FROM properties WHERE owner_citizenid = @citizenid", {
        ['@citizenid'] = citizenid
    })

    if result and #result > 0 then
        for i = 1, #result do
            table.insert(properties, result[i])
        end
    end

    return properties
end

**Comment by TankinTom** [comment]
a clean re-install seems to have fixed the issue

**Comment by MonkeyWhisper** [comment]
Do not open issues for support.
