### ISSUE TITLE
Waypoints from dispatch not compatible with ps-dispatch v2 calls

### ISSUE THREAD

**Issue by mikepauer** [Project-Sloth/ps-mdt#397]
Looks like in ps-dispatch v2 the alert coords are located in coords.xyz while dispatch v1 had them in origin.xyz.

mdt:client:setWaypoint in client.lua needs to be adapted to handle this.

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/pull/398
