### ISSUE TITLE
Edit after creation / deleting charges

### ISSUE THREAD

**Issue by gerardojro** [Project-Sloth/ps-mdt#4]
After I create an incident report and try to update it, for some reason it's not saving.

Second issue: Once you add a charge you can't delete it.

**Comment by pushkart2** [comment]
right click on that charge in the charge section to delete it

**Comment by gerardojro** [comment]
Tried it. Doesn't work

**Comment by MonkeyWhisper** [comment]
For all support questions, ask in our Discord support chat.
https://discord.gg/loljoshie
