### ISSUE TITLE
Unable to remove charges / Charges disappear when attempting to remove in incidents.

### ISSUE THREAD

**Issue by AngryMaximus** [Project-Sloth/ps-mdt#409]
After the new WIP stacked charges, When attempting to remove the charges from the criminal, the charges disappear on the top bar and do not get removed. 
Charges also do not stack immediately and only stack once saved and switch to a different tab and switching back.

**Comment by MonkeyWhisper** [comment]
> After the new WIP stacked charges, When attempting to remove the charges from the criminal, the charges disappear on the top bar and do not get removed. Charges also do not stack immediately and only stack once saved and switch to a different tab and switching back.

Is WIP and it's not pushed to live at all, it's not finished
