### ISSUE TITLE
Incidents Are "Re-Saving"

### ISSUE THREAD

**Issue by X-Emerald** [Project-Sloth/ps-mdt#410]
When you create an incident report hit save then go back into and edit it change some of the info in the summary box etc.... hit save again then go back into it and it will revert back to the previous save,

its like it won't overwrite the save from the first time?

**Comment by MonkeyWhisper** [comment]
Your title made no sense. 

You meant to say Incidents are NOT SAVING, not re-saving. 

Anyways, I fixed it.

https://github.com/Project-Sloth/ps-mdt/pull/411
