### ISSUE TITLE
Not able to search profiles

### ISSUE THREAD

**Issue by chadworth94** [Project-Sloth/ps-mdt#422]
I am not able to search profiles. This is the error I recieve.

[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:256: ps-mdt was unable to execute a query!
[      script:qb-core] Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
[      script:qb-core] SELECT p.citizenid, p.charinfo, md.pfp, md.fingerprint FROM players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(CONCAT(JSON_VALUE(p.charinfo, '$.firstname'), ' ', JSON_VALUE(p.charinfo, '$.lastname'))) LIKE ? OR LOWER(`charinfo`) LIKE ? OR LOWER(`citizenid`) LIKE ? OR LOWER(md.fingerprint) LIKE ? AND jobtype = ? LIMIT 20 ["%austin riley%","%austin riley%","%austin riley%","%austin riley%","police"]
[      script:qb-core] > ref (@ps-mdt/server/main.lua:256)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22255)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] > async rawQuery (@oxmysql/dist/build.js:22223)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:365)
[      script:qb-core] > handler (@qb-core/server/events.lua:104)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22255)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] > async rawQuery (@oxmysql/dist/build.js:22223)

**Comment by LeSiiN** [comment]
Instead of creating a issue in here, try the support channel in our discord, this problem got fixed several times

**Comment by chadworth94** [comment]
I did try to join discord but the link is not available for me. If you have a good link, ill be happy to take it to discord.

**Comment by massfright** [comment]
the discord was not helpful only support channel i see is support-project
