### ISSUE TITLE
ps-mdt error

### ISSUE THREAD

**Issue by OSG59401** [Project-Sloth/ps-mdt#425]
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:256: ps-mdt was unable to execute a query!
[      script:qb-core] Query: SELECT p.citizenid, p.charinfo, md.pfp, md.fingerprint FROM players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(CONCAT(JSON_VALUE(p.charinfo, '$.firstname'), ' ', JSON_VALUE(p.charinfo, '$.lastname'))) LIKE ? OR LOWER(`charinfo`) LIKE ? OR LOWER(`citizenid`) LIKE ? OR LOWER(md.fingerprint) LIKE ? AND jobtype = ? LIMIT 20
[      script:qb-core] ["%n%","%n%","%n%","%n%","police"]
[      script:qb-core] Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
[      script:qb-core] > ref (@ps-mdt/server/main.lua:256)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24894)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25061)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:365)
[      script:qb-core] > handler (@qb-core/server/events.lua:104)
[      script:qb-core] > logError (@oxmysql/dist/build.js:24894)
[      script:qb-core] > rawQuery (@oxmysql/dist/build.js:25061)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

ps-mdt\server\main.lua 
line 256:
local people = MySQL.query.await("SELECT p.citizenid, p.charinfo, md.pfp, md.fingerprint FROM players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(CONCAT(JSON_VALUE(p.charinfo, '$.firstname'), ' ', JSON_VALUE(p.charinfo, '$.lastname'))) LIKE :query OR LOWER(`charinfo`) LIKE :query OR LOWER(`citizenid`) LIKE :query OR LOWER(md.fingerprint) LIKE :query AND jobtype = :jobtype LIMIT 20", { query = string.lower('%'..sentData..'%'), jobtype = JobType })

**Comment by lenzh** [comment]
get in discord for support

**Comment by Th3shitshows** [comment]
whats the discord?
