### ISSUE TITLE
Add back "Respond to Call" feature for Recent Calls

### ISSUE THREAD

**Issue by Gnavling** [Project-Sloth/ps-mdt#431]
In prior versions, there was an option to respond to 911 and 311 calls with text. It was a great feature feature for RP. If possible I think it would be a great addition to the newer versions.

**Comment by MonkeyWhisper** [comment]
Use ps-dispatch for this now

**Comment by Gnavling** [comment]
@MonkeyWhisper ps-dispatch lets you respond with text? I'm only able to find the functionality to attach to the calls. But I remember the older MDT versions had the sendCallResponse event.
