### ISSUE TITLE
i cant serach for anyone

### ISSUE THREAD

**Issue by Th3shitshows** [Project-Sloth/ps-mdt#433]
![Screenshot 2023-12-07 211901](https://github.com/Project-Sloth/ps-mdt/assets/107448407/a515e66e-79e3-4deb-bdb8-e1356983e924)
i have reinstalled several times. and i am not to sure what i am missing.. any help would be greatly appreciated. thank you

**Comment by Th3shitshows** [comment]
![Screenshot 2023-12-07 212445](https://github.com/Project-Sloth/ps-mdt/assets/107448407/23180189-b6c5-4241-879f-377c09e5d4b6)

**Comment by Oblisk87** [comment]
Just read the readme...

Getting a error about utf8mb4_unicode illegal collation? - QBCore has decided to change their collations on the new txAdmin recipe, change your collation on your players table to utf8mb4_general_ci.

**Comment by Oblisk87** [comment]
https://i.imgur.com/XDNlDzk.png

**Comment by WolfpackChloe** [comment]
You just need to edit the collation in the table on your database for players as shown above in image
