### ISSUE TITLE
I can't search profiles.

### ISSUE THREAD

**Issue by igadeath** [Project-Sloth/ps-mdt#439]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-mdt/server/main.lua:256: ps-mdt was unable to execute a query!
[      script:qb-core] Query: SELECT p.citizenid, p.charinfo, md.pfp, md.fingerprint FROM players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(CONCAT(JSON_VALUE(p.charinfo, '$.firstname'), ' ', JSON_VALUE(p.charinfo, '$.lastname'))) LIKE ? OR LOWER(`charinfo`) LIKE ? OR LOWER(`citizenid`) LIKE ? OR LOWER(md.fingerprint) LIKE ? AND jobtype = ? LIMIT 20

**Comment by JericoFX** [comment]
what version of mysql do you use?

**Comment by igadeath** [comment]
| version()                        |
+----------------------------------+
| 10.3.38-MariaDB-0ubuntu0.20.04.1
Is this answer correct?
I'm new to this kind of thing.
I'm sorry if my English is not good enough.

**Comment by JericoFX** [comment]
did you import the mdt sql into the database?

**Comment by igadeath** [comment]
I did import it.

**Comment by Oblisk87** [comment]
Did you change change the Player database ?


- **Getting a error about utf8mb4_unicode illegal collation?** - QBCore has decided to change their collations on the new txAdmin recipe, change your collation on your players table to utf8mb4_general_ci.
![image](https://i.imgur.com/XDNlDzk.png )

**Comment by igadeath** [comment]
That was the problem. Thank you so much!

**Comment by Oblisk87** [comment]
Your welkome:)

**Comment by eufivem** [comment]
Thank you so much!
