### ISSUE TITLE
F8 log error

### ISSUE THREAD

**Issue by WolfpackChloe** [Project-Sloth/ps-mdt#442]
I am new to coding and still learning, how do i fix this please, thank you

<img width="1376" alt="ps-mdt error" src="https://github.com/Project-Sloth/ps-mdt/assets/58238399/7484c7a9-de99-4225-836a-b3877164b852">

**Comment by LeSiiN** [comment]
this should be discused in our discord, just join our discord and head to live-support there are people there that will help u.

But a quick fix would be, removing the ) in line 1119 and adding it behind the ,,end'' in line 1117
