### ISSUE TITLE
Reports and ICU reports not saving

### ISSUE THREAD

**Issue by RafaelLopes98** [Project-Sloth/ps-mdt#445]
![FiveM_b2944_GTAProcess_A6ZgyESHBZ](https://github.com/Project-Sloth/ps-mdt/assets/79937843/a1a0f643-7c4f-4750-9678-6f908185e58e)

I checked every file after traductions, not an sql import error

**Comment by smokeddrinks** [comment]
im getting same problem

**Comment by MonkeyWhisper** [comment]
Yes they do save.
