### ISSUE TITLE
Doj Jobs Not being able to see their own reports

### ISSUE THREAD

**Issue by AngryMaximus** [Project-Sloth/ps-mdt#446]
So with the config jobType tagging reports written by doj jobs as doj in the database when creating reports
Any doj member can receive police 'reports' but can't receive doj 'reports' due to the report server section changing doj to police type

![tJk3ipd](https://github.com/Project-Sloth/ps-mdt/assets/49353238/238fc3d1-4810-4c84-bd1d-7b82003777a2)

![wZ2KgCB](https://github.com/Project-Sloth/ps-mdt/assets/49353238/f9967511-ee8c-4926-95b3-03392f1a4e34)

**Comment by MonkeyWhisper** [comment]
No that's not why 

When an original report is created by police, it sets the type to police and cannot be view/edited by DOJ. It was designed like so
