### ISSUE TITLE
Profiles not showing

### ISSUE THREAD

**Issue by Beaker9191** [Project-Sloth/ps-mdt#452]
![image](https://github.com/Project-Sloth/ps-mdt/assets/152914343/d5a50fca-6231-44b2-90cd-100e38d708fc)

I need help

**Comment by Beaker9191** [comment]
How are you gonna complete this with no answer at all

**Comment by MonkeyWhisper** [comment]
> How are you gonna complete this with no answer at all

Can't you read? Your ERROR is there and if you read the README, you will also find your answer. 

That is why we closed it with no answer, learn to read and stop creating issues.

**Comment by Beaker9191** [comment]
Where is the answer cause what i see there is an error in the SQL that came with the file. And thje readme doesnt say jack about that
