### ISSUE TITLE
Issue while searching for a profile

### ISSUE THREAD

**Issue by slvator** [Project-Sloth/ps-mdt#457]
Some profiles gets glitched if you save them, get this error in F8:
PS-MDT:nui: CrBrowserMain/ Uncaught (in promise) ReferenceError: licenseTypesGlobal is not defined (@ps-mdt/ui/app.js:5586)
![Capture](https://github.com/Project-Sloth/ps-mdt/assets/76708037/378f6515-bfee-40d3-a133-9f774d4b1165)

**Comment by pixelift** [comment]
Am sorry but we are having exactly the same issue, seems like licenseTypesGlobal went missing, it is not defined anywhere nor I cant find any commit with it. Any ideas?
