### ISSUE TITLE
Map not work.

### ISSUE THREAD

**Issue by ELFREAL** [Project-Sloth/ps-mdt#459]
Map not work. QB Framework - latest,
![2024-03-06_05-53-55](https://github.com/Project-Sloth/ps-mdt/assets/121699551/5f5baaa3-50c7-439a-b951-6af30aa870cc)

**Comment by DopeLovingHippy** [comment]
yeah having same issue

**Comment by MonkeyWhisper** [comment]
Update the image

**Comment by DopeLovingHippy** [comment]
> Update the image

where is the image location mate ?

**Comment by ELFREAL** [comment]
> Update the image
Please tell me which image to update and where.

**Comment by ShiftyWreckzz** [comment]
@ELFREAL @DopeLovingHippy 
If you are still having this issue, go to line 5791 in ui/apps.js :
`var customImageUrl = 'https://i.imgur.com/EdOZjzF.jpg';`
And simply change/update the link.
