### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jazzy-80** [Project-Sloth/ps-mdt#461]
I am getting an error when installing, can you help?

![mdt](https://github.com/Project-Sloth/ps-mdt/assets/130931652/4af24d90-6bf7-483a-9022-85f3faca4221)

**Comment by TheRealCyb3r** [comment]
Yep I am facing a similar error
![Capture223](https://github.com/Project-Sloth/ps-mdt/assets/135444258/388eaed9-4ccd-49de-b982-021463e99660)

**Comment by DopeLovingHippy** [comment]
i had to change to (utf8mb4_general_ci) from (utf8mb4_unicode_ci) in my database  i can't see the full error but it looks like you both need to do that for CHARINFO under PLAYER in your database

**Comment by DopeLovingHippy** [comment]
<img width="1272" alt="help" src="https://github.com/Project-Sloth/ps-mdt/assets/92433500/56880e27-f1ec-4646-9f58-fd0a8c7e3961">

**Comment by Jazzy-80** [comment]
![Screenshot_181](https://github.com/Project-Sloth/ps-mdt/assets/130931652/3cd2c8b5-d275-4720-9933-1ec7b9f1da6f)
I have looked at this and it is set to what you have in your screenshot

**Comment by DopeLovingHippy** [comment]
> ![Screenshot_181](https://private-user-images.githubusercontent.com/130931652/313025055-3cd2c8b5-d275-4720-9933-1ec7b9f1da6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjUwMjEsIm5iZiI6MTcxMDQ2NDcyMSwicGF0aCI6Ii8xMzA5MzE2NTIvMzEzMDI1MDU1LTNjZDJjOGI1LWQyNzUtNDcyMC05OTMzLTFlYzdiOWYxZGE2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwMTA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTlmN2RiOTVjZGY2OTNjNmQ1MWFmYzE5OTg2MDljZmZhODc4ZTI0MTQzZWExMzA5NzMzZmYxYzgxMjI5ZmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.08KYUyPv-rnX-F87vLI7nCmVVWL4gkzIEe8P9CuPe9o) I have looked at this and it is set to what you have in your screenshot

you have it set to (utf8)   ...... its mean't to be (utf8mb4)

**Comment by Jazzy-80** [comment]
Do I just change the CHARINFO one?

**Comment by Jazzy-80** [comment]
I have just changed the charinfo one but still getting the same info, I have asked on their discord but not getting any help

**Comment by MonkeyWhisper** [comment]
Read the read me. Stop spamming this.
