### ISSUE TITLE
MDT Issue

### ISSUE THREAD

**Issue by ukmob1980** [Project-Sloth/ps-mdt#462]
![Screenshot_182](https://github.com/Project-Sloth/ps-mdt/assets/163959483/5710f9f0-16dd-4d88-a648-294b66e66cc1)

![Screenshot_183](https://github.com/Project-Sloth/ps-mdt/assets/163959483/9c559670-7117-460d-8a39-bec7a8d721a6)
Hello. I have just put in the mdt into my city, when I look up someone it comes up with the following error, as you can see in the pictures I have read the readme and looked through previous issues on here but I am still getting this error. Is there a way to fix this please?

**Comment by Jazzy-80** [comment]
Hello, Can you tell me why this is closed as I don't see a response.

**Comment by ukmob1980** [comment]
Hello, Can you tell me why this is closed as I don't see a response.
