### ISSUE TITLE
Displays the profiles recently edited

### ISSUE THREAD

**Issue by CKRACER** [Project-Sloth/ps-mdt#471]
When I search for a profile on MDT, it displays the profile I searched for, as well as recently edited profiles. When it should display only the profile i searched for. Under is a image where i show it. I search for a profile of Asasda, and it shows it, and another three profiles i recently edited
https://cdn.discordapp.com/attachments/900180032935325707/1241645192403222559/image.png?ex=664af3b2&is=6649a232&hm=72146aac9313cd0d77366152ac9328b9395991600873e6dbf25cd895b3a49f34&

**Comment by xFutte** [comment]
Screenshot not available. Closing.
