### ISSUE TITLE
Active Units list showing people out of the server

### ISSUE THREAD

**Issue by Slayyin** [Project-Sloth/ps-mdt#49]
Have been toying with it for awhile and cannot figure out how to make it so people who disconnect dont show up on active units list. Right now, the list gets riddled with people as the day goes on since it doesnt remove people who have Dc'd, and people who clock off duty just show as 10-7 instead of disappearing as well.

**Comment by MonkeyWhisper** [comment]
Featured will be added later, this is not a breaking issue
