### ISSUE TITLE
XSS In char names appending

### ISSUE THREAD

**Issue by Infinity585** [Project-Sloth/ps-mdt#495]
I have made a pull request fixing an XSS within the dispatch chat while testing I have discovered another XSS attack that can be done using character names by setting my last name as <script> alert(0) </script> when I open the mdt an alert box comes up. As well as each time I send a message I get an alert box.

**Comment by MonkeyWhisper** [comment]
Yeah, there is a lot of XSS, thanks for catching those. Our ps-mdt v2 will be completed soon as well and those will be patched
