### ISSUE TITLE
blank map and ems calls not showing 

### ISSUE THREAD

**Issue by sabotage93thctv** [Project-Sloth/ps-mdt#496]
![Screenshot 2024-09-16 001751](https://github.com/user-attachments/assets/0d4f626b-2782-4555-b37f-78a2dcbc684a)
![Screenshot 2024-09-16 001805](https://github.com/user-attachments/assets/2d96ac2e-8b34-44de-aecc-8155624d330a)

this is all we get after a call but we do get a notification to say a call came in but then nothing plus no map showing :L

**Comment by sabotage93thctv** [comment]
lol yet again typical in this community broken scripts devs wont admit

**Comment by MonkeyWhisper** [comment]
> lol yet again typical in this community broken scripts devs wont admit

Yet you come asking for help on something that already has been fixed? Typical of "self titled devs" like yourself.

Go fly a kite.
