### ISSUE TITLE
White Map

### ISSUE THREAD

**Issue by NeptuxKRP** [Project-Sloth/ps-mdt#497]
Hey! I have the mdt and ps-dispatch too. When i open mdt it has a white map on it and cant interact with it.

**Comment by Xergxes7** [comment]
Need to update "customImageUrl" in app.js line 5791 to a link that works, however do not know what the dimension must be, have asked on the discord

**Comment by xFutte** [comment]
> Need to update "customImageUrl" in app.js line 5791 to a link that works, however do not know what the dimension must be, have asked on the discord

Dimensions don't matter as long as the map is right. Make a PR with the updated link if you want to.

**Comment by Xergxes7** [comment]
fixed in my custom fork(I have a lot of integration changes in my own code):
app.js 
``
var customImageUrl = 'https://i.ibb.co/w6wVBLs/FixedMap.jpg';
``
