### ISSUE TITLE
Can't find profile in MDT

### ISSUE THREAD

**Issue by ansljeremy** [Project-Sloth/ps-mdt#499]
Can't find person when searching in MDT. Attached is image of the error.
![image](https://github.com/user-attachments/assets/b7dd0680-ef99-49a3-9490-f39c40753270)

**Comment by ansljeremy** [comment]
@MonkeyWhisper this was not fixed in the last commit which is why I assume you marked this as completed.

**Comment by MonkeyWhisper** [comment]
You fix it.
