### ISSUE TITLE
Ems/officer on duty

### ISSUE THREAD

**Issue by KevinGirardx** [Project-Sloth/ps-mdt#5]
So in the mdt if you are police an onduty it shows fine however ems on duty also shows up as lspd under the active officer

**Comment by pushkart2** [comment]
Can you share a image of this?

**Comment by NoobySloth** [comment]
Hey! I can provide a photo! :) | So, the first photo is me on the AMBULANCE MDT, the second photo is an officer on duty...
![image](https://user-images.githubusercontent.com/6962192/162101945-ad7bcdd4-7fc0-4ca6-8ba5-d617511077c0.png)

![image](https://user-images.githubusercontent.com/6962192/162101964-c4db063b-6231-4204-8411-22817813d08e.png)

**Comment by CreelEU** [comment]
Same issue

**Comment by NoobySloth** [comment]
![image](https://user-images.githubusercontent.com/6962192/163262849-b185c470-bf9f-4beb-a7c1-423308f03efe.png)
Same for lawyers, his job is lawyer
![image](https://user-images.githubusercontent.com/6962192/163262894-88a273c2-e64b-4a03-baee-0282c3957417.png)

**Comment by pushkart2** [comment]
I am unable to reproduce this. Does this happen with multiple clients? Do I need multiple clients to test this?

**Comment by CreelEU** [comment]
> I am unable to reproduce this. Does this happen with multiple clients? Do I need multiple clients to test this?

You'll need more than one client to have this happen

**Comment by HATE-dev** [comment]
i tried with my firend it shows him as ambulance while he was police and show his job as unknown.

**Comment by pushkart2** [comment]
did you set the jobs in game or restart the script?

**Comment by HATE-dev** [comment]
> did you set the jobs in game or restart the script?

i ddnt restart the script and yeah i set job with command

**Comment by Polodevs** [comment]
Same issue for me this is not good as it means all bankrobberys and illegal activities can be done if only ems are on duty, as they show up as police. Also Police show up as Unkown on the EMS MDT 

 please see attached images
![unknown](https://user-images.githubusercontent.com/98401022/164701625-c7b81d39-070e-4b36-814c-a91b8337d91f.png)
![FiveM_b2372_GTAProcess_hGW8PVUjRm](https://user-images.githubusercontent.com/98401022/164701646-2f340686-cb3c-4c6e-b2ee-e89503ef25cb.png)

**Comment by KevinGirardx** [comment]
> Same issue for me this is not good as it means all bankrobberys and illegal activities can be done if only ems are on duty, as they show up as police. Also Police show up as Unkown on the EMS MDT
> 
> please see attached images ![unknown](https://user-images.githubusercontent.com/98401022/164701625-c7b81d39-070e-4b36-814c-a91b8337d91f.png) ![FiveM_b2372_GTAProcess_hGW8PVUjRm](https://user-images.githubusercontent.com/98401022/164701646-2f340686-cb3c-4c6e-b2ee-e89503ef25cb.png)

This does not have anything to do with cops or as you are daying ems requirements for robberies tho, it just a list for emergency services to see who is on duty

**Comment by HATE-dev** [comment]
when its gna get fixed
