### ISSUE TITLE
ps-mdt and ps-housing issue

### ISSUE THREAD

**Issue by ghost** [Project-Sloth/ps-mdt#504]
When using ps-mdt and ps-housing. There is a problem where if you have a house that is a MLO. THe script cannot get the coords since it doesnt save coords in the door data table. Which makes it so you cant see that persons properties. Any fixes?

**Comment by ghost** [comment]
how is this completed?

**Comment by Llama-Palooza** [comment]
Getting the same issue, fresh download of both mdt and housing
The MDT seems to fetch coords from the door_data, but for MLO houses it doesn't save the same as shells, so the mdt bugs out.
![image](https://github.com/user-attachments/assets/7c29696a-e5d7-48c8-845a-a3e5136c9c27)

**Comment by ghost** [comment]
Yeah dev doesn’t seem to care though since he just closed it with no response

**Comment by Llama-Palooza** [comment]
![image](https://github.com/user-attachments/assets/26f6978e-e473-4ea9-856a-7badb5f8eb8e)

This seems to work, for now. As long as a garage is set, it'll grab the coords from that.

**Comment by ghost** [comment]
Okay thanks!

**Comment by Llama-Palooza** [comment]
No worries. At least the dev knows it's an issue and can be patched with the next update. Monkey is a good dude, be patient with him haha. 

Thank goodness it's open source though, edits can easily be done to help them get it patched while they work on other things, like ps-inventory V2. :)

**Comment by ghost** [comment]
Yeah i know. Making such cool scripts and for free nowadays is rare

**Comment by MonkeyWhisper** [comment]
> Yeah dev doesn’t seem to care though since he just closed it with no response

Fuck off pos.

**Comment by MonkeyWhisper** [comment]
> ![image](https://private-user-images.githubusercontent.com/124511433/396308419-26f6978e-e473-4ea9-856a-7badb5f8eb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDAwODAsIm5iZiI6MTczNDM5OTc4MCwicGF0aCI6Ii8xMjQ1MTE0MzMvMzk2MzA4NDE5LTI2ZjY5NzhlLWU0NzMtNGVhOS04NTZhLTdiYWRiNWY4ZWI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwMTQzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmE4N2YwNGJlYmI1OTc2MWNlMGZiNWRhNTczN2Y3NzI2YWFmMTkxMWM5Mzc3YjAyMTQyZGQ1NDAwMzNlMjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hy2ucancIa_du5Sz1o9Tv0sAQF0C8bNw_tst01hcveM)
> 
> This seems to work, for now. As long as a garage is set, it'll grab the coords from that.

Can you send a PR? I'd appreciate it
