### ISSUE TITLE
Fines and Sentances Show up the same for 2 people.

### ISSUE THREAD

**Issue by Xandrice** [Project-Sloth/ps-mdt#55]
When I create an incident, once I add both suspects to the charges, it takes the most recent person's time and fines and sets it to both individuals. 
First individual (Albert) was added and charges were added. Then second individual (Clee) was added and when fines were selected, Alberts fines and times were changed. 
I am using the latest version of ps-mdt
![image](https://user-images.githubusercontent.com/48589989/170820560-29086eab-bf70-4e9b-8a9f-5a22b3d0c74c.png)

Also tried it again with just adding both suspects
![image](https://user-images.githubusercontent.com/48589989/170820828-16db3bf8-fec4-4787-88ee-6c6ba44ffd62.png)

**Comment by MonkeyWhisper** [comment]
Already reported here

https://github.com/Project-Sloth/ps-mdt/issues/57
