### ISSUE TITLE
ANPR locations to report BOLO vehicles

### ISSUE THREAD

**Issue by ModoSN** [Project-Sloth/ps-mdt#56]
Config to set locations of ANPR "cameras" and then driving past them with a BOLO vehicle triggers a ps-dispatch?

**Comment by JoeSzymkowiczFiveM** [comment]
We are always accepted PRs but imagining how those would be implemented, it would mean every client passing through an ANPR light would be querying BOLOs each time, which is a lot of added overhead for an interesting, but unnecessary feature. Closing this issue.
