### ISSUE TITLE
Adding images to gallery in the BOLO page does not save

### ISSUE THREAD

**Issue by DeputyDutch** [Project-Sloth/ps-mdt#68]
I've already updated my MDT and I plan to try an fix the issue myself but as it stands images don't save on the gallery under the BOLO section of the mdt. They save everywhere else but BOLO.

**Comment by DeputyDutch** [comment]
Checked the database calls, don't see anything wrong yet xD

edit: Yeah I'm really stumped on this one I can't find any typos or anything. Maybe I've just overlooked it though so I'll keep pluggin at it.

**Comment by MonkeyWhisper** [comment]
Join Discord for support. discord.gg/projectsloth
