### ISSUE TITLE
Known Convictions / incident charges

### ISSUE THREAD

**Issue by TonybynMp4** [Project-Sloth/ps-mdt#69]
It'd be cool to have a 2x, 3x etc before the charge to see how many times the person has been convicted with this charge (currently even if you've been arrested 20 times for simple assault it'll only show it once)
Also instead of seeing the charges multiple times use the same time x charge in the incidents reports.

**Comment by MonkeyWhisper** [comment]
No taking any improvements right now.

**Comment by TonybynMp4** [comment]
> No taking any improvements right now.

still not ? it would be neat
