### ISSUE TITLE
Profiles Un-Searchable - SQL Error

### ISSUE THREAD

**Issue by WhoopsIJust** [Project-Sloth/ps-mdt#73]
Currently if i try to serach any profiles i get an error in my server console, I have checked all the provided SQL tables follow. This is the query that has the issues under server event: 'mdt:server:incidentSearchPerson'

local result = MySQL.query.await("SELECT p.citizenid, p.charinfo, md.pfp from players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(`charinfo`) LIKE :query OR LOWER(`citizenid`) LIKE :query AND `jobtype` = :jobtype LIMIT 30", {
					query = string.lower('%'..query..'%'), -- % wildcard, needed to search for all alike results
					jobtype = JobType
				})

constantly provides error: JSON_VALUE does not exist in server console.

**Comment by MonkeyWhisper** [comment]
Seems like an isolated issue with your self only
