### ISSUE TITLE
EMS mdt does not populate calls for workers to attach to

### ISSUE THREAD

**Issue by jerzzy510** [Project-Sloth/ps-mdt#74]
When an EMT/Medic is on duty and receives a call for service same does not populate in the calls section. The dispatch notifications work properly and gives the signal. Police are able to see the calls for service, attach themselves, gps etc. just not the ambulance job.

Everything else in the mdt is beautiful with zero issues. Thank you so much for the quick help and responses ! Looking forward to hearing back with the results !!

**Comment by MonkeyWhisper** [comment]
This is not a feature right now
