### ISSUE TITLE
Unable to remove dispatch blips

### ISSUE THREAD

**Issue by AkinoKitsu** [Project-Sloth/ps-mdt#76]
If you open the MDT and right click > remove blip in the calls section, the call and blip are not removed as expected.

**Comment by MonkeyWhisper** [comment]
Not all gets removed

**Comment by JoeSzymkowiczFiveM** [comment]
Use `cleardispatchblips`

**Comment by AkinoKitsu** [comment]
> Use `cleardispatchblips`

This is part of ps-dispatch, and removes *all* blips, rather than the selected blip.


@MonkeyWhisper 
> Not all gets removed

NONE get removed. I have tried on several types of calls, and you are unable to remove any calls, individually, not for all calls.
Issues needs to be re-opened.

**Comment by MonkeyWhisper** [comment]
> > Use `cleardispatchblips`
> 
> This is part of ps-dispatch, and removes _all_ blips, rather than the selected blip.
> 
> @MonkeyWhisper
> 
> > Not all gets removed
> 
> NONE get removed. I have tried on several types of calls, and you are unable to remove any calls, individually, not for all calls. Issues needs to be re-opened.

No, issues does not need to be re-opened. 

You are able to remove all DISPATCH blips from the MAP. Works 100%, I just tested. 

Blips, not calls, blips. Read what the command does.

**Comment by JoeSzymkowiczFiveM** [comment]
> > Use `cleardispatchblips`
> 
> This is part of ps-dispatch, and removes _all_ blips, rather than the selected blip.
> 
> @MonkeyWhisper
> 
> > Not all gets removed
> 
> NONE get removed. I have tried on several types of calls, and you are unable to remove any calls, individually, not for all calls. Issues needs to be re-opened.

Remove blip for a single alert was added in 646a457.

**Comment by AkinoKitsu** [comment]
@MonkeyWhisper 
Please re-read the issue.
I am *not* talking about /cleardispatchblips. This issue is on ps-mdt, not ps-dispatch.

The command to remove ALL BLIPS works fine.
The feature in the MDT to remove a specific call AND it's blip from MDT AND dispatch (map) is not working.
It *was* working in an earlier version, only stopped working after I updated my installation at some point.
