### ISSUE TITLE
Wont open /mdt

### ISSUE THREAD

**Issue by DoVaRemix** [Project-Sloth/ps-mdt#81]
SCRIPT ERROR in promise (unhandled): Error: mdt was unable to execute a query!
[ script:oxmysql] Table 'zap917420-1.mdt_reports' doesn't exist
[ script:oxmysql] SELECT * FROM (SELECT * FROM `mdt_reports` ORDER BY `id` DESC LIMIT 3) sub ORDER BY `id` DESC []

**Comment by JericoFX** [comment]
you need to import the mdt.sql

**Comment by ikrazy99** [comment]
Having the same issue, uploaded the sql properly and double checked db.

**Comment by JericoFX** [comment]
if the error is this `Table 'zap917420-1.mdt_reports' doesn't exist `, thats means the sql wasnt properly created.

**Comment by ikrazy99** [comment]
https://cdn.discordapp.com/attachments/900180032935325707/999057587750314094/unknown.png

**Comment by MonkeyWhisper** [comment]
This is not for support. Join our Discord for help. discord.gg/projectsloth
