### ISSUE TITLE
Unexpected behavior with profile notes between separate jobs

### ISSUE THREAD

**Issue by jnccloud** [Project-Sloth/ps-mdt#82]
Hey guys, Castar here. 

When writing notes onto a civilian's profile, the notes appear to be assigned the wrong job and break the profile note functionality. A message from a player:

> Done some testing with Cpt Smith, any comments put in by PD come through to the EMS MDT and then they can't see them and only EMS can. EMS comments don't seem to go through to PD from the testing we did. Only seems to happen on some profiles or maybe only recent comments

IIRC some information is linked to the job that created it, but I'm unsure if profile information is. Either way, something is funky with it. 

Maybe the issue stems from what job wrote the first note?

**Reproduce:**

- Write a note in someone's profile as police
- Have another person in another job read that persons profile and/or try to edit that note as ambulance or judge
- Note will either A) Show up or B) Behave oddly when trying to edit
- Unsure if reproducible if you change your own job in the same session

**Expected behavior:**

- Notes only appear for the job that created them on a civilian's profile
- Medical notes are especially sensitive because they can reveal information about a civilian that could be used against them by LEO
- Each job should have their own version of the notes field so that it is in relation to their job; any shared information should be given through RP and it be up to that job to add it if needed. 
- Example: It makes no sense to have a person's blood type or allergies listed for LEO or DOJ
- Example 2: It makes no sense to have a person's bail amount or criminal notes showing for EMS

I believe it was originally intended for these notes to be separate, which is why I am creating the issue. If this is not the case, please close. But based on the SQL and differing layouts and permissions for the separate jobs, I am led to believe it should be separate.

Possibly related to #77

**Comment by SerenaKing** [comment]
# Note
*When I personally used `ps-mdt` I couldn't repricate this issue. Not on my EMS character or PD Character.*

# Question
*Could you provide more information from the console? Both Server & Client. Are you running the latest possible version with the SQL injected the proper way? Rec: HeidiSQL*
