### ISSUE TITLE
Bug | Police MDT | BOLO's

### ISSUE THREAD

**Issue by Xandrice** [Project-Sloth/ps-mdt#87]
When writing a BOLO, photos, tags and anything else on the right side of the screen doesn't save when you save the BOLO. 
Tested with the latest MDT download, and a fresh install.

**Comment by xxUnknown13xx** [comment]
Does it save now?

**Comment by MonkeyWhisper** [comment]
Fixed https://github.com/Project-Sloth/ps-mdt/pull/104
