### ISSUE TITLE
Bug | Multi Police Jobs not working

### ISSUE THREAD

**Issue by TheCrypticOG** [Project-Sloth/ps-mdt#88]
The issue is when you change your job to a job outside of "police" the profiles do not load correctly. I have my job set at bcso which is set to true in the config and none of the profile information loads and the dept is set to unknown on the home page
![Code_GifbF88CJM](https://user-images.githubusercontent.com/98983638/181085509-d61c8999-097e-480e-a4f1-325df98692ba.png)
![FiveM_b2372_GTAProcess_N26VmIlPFK](https://user-images.githubusercontent.com/98983638/181085584-8ffb54cb-8326-4535-bfcd-9a644fde84c2.png)
.

**Comment by TheCrypticOG** [comment]
Also having the same issue with ps-dispatch where none of the police jobs except for the actual job "police" receive the calls

**Comment by TheCrypticOG** [comment]
So after furhter investigation ive found that you have to set them in the app.js
The issue is is now it says I'm part of LSPD or Ambulance when I'm apart of Fire or BCS
![Code_XMeOsrhRWi](https://user-images.githubusercontent.com/98983638/182037228-2bd09aff-f3aa-4705-a62c-3491e520bcf9.png)
![FiveM_b2372_GTAProcess_GuuIG206T5](https://user-images.githubusercontent.com/98983638/182037238-679ae952-cc91-4548-8d3b-6229940387cb.png)

**Comment by MonkeyWhisper** [comment]
This isn't an issue, this was actually part of the FAQ on our Docs.
