### ISSUE TITLE
Error when search for player

### ISSUE THREAD

**Issue by Svenhr** [Project-Sloth/ps-mdt#93]
When try to search for player this show in server console

[      script:qb-core] SCRIPT ERROR: SCRIPT ERROR: ps-mdt was unable to execute a query!
[      script:qb-core] FUNCTION qbcoreframework_f1c44a.JSON_VALUE does not exist
[      script:qb-core] SELECT p.citizenid, p.charinfo, md.pfp FROM players p LEFT JOIN mdt_data md on p.citizenid = md.cid WHERE LOWER(CONCAT(JSON_VALUE(p.charinfo, '$.firstname'), ' ', JSON_VALUE(p.charinfo, '$.lastname'))) LIKE ? OR LOWER(`charinfo`) LIKE ? OR LOWER(`citizenid`) LIKE ? OR LOWER(`fingerprint`) LIKE ? AND jobtype = ? LIMIT 20 ["%sven krusinski%","%sven krusinski%","%sven krusinski%","%sven krusinski%","police"]
[      script:qb-core] > ref (@ps-mdt/server/main.lua:122)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:21749)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] > async rawQuery (@oxmysql/dist/build.js:21719)
[      script:qb-core] 
[      script:qb-core] (nil stack trace)Server list query returned an error:

**Comment by JericoFX** [comment]
do you use xampp or lagaron?, also what version of mysql do you use?

**Comment by Svenhr** [comment]
Im using wamp server and mysql version is 5.7.36

This guy here i help me to fix sql file for my sql version https://stackoverflow.com/questions/73295433/mysql-all-parts-of-primary-key-must-be-not-null-if-you-need-null-in-a-key-use

Maybe is this cause this error?

Also i have question what is recomended sql version for you qb framevork?

**Comment by Svenhr** [comment]
I made little change is sql file beacuse defult file cant be upload on my database version

**Comment by Svenhr** [comment]
This guy here i help me to fix sql file for my sql version

https://stackoverflow.com/questions/73295433/mysql-all-parts-of-primary-key-must-be-not-null-if-you-need-null-in-a-key-use

**Comment by Svenhr** [comment]
Maybe is this cause this error?

**Comment by Svenhr** [comment]
Alo i have question what is recomended sql version for you qb framevork?

**Comment by JericoFX** [comment]
versión 5.7 doesn't support JSON_value, one sugestion is upgrade mysql or in server.lua change JSON_VALUE to JSON_EXTRACT

**Comment by Svenhr** [comment]
Hi this is a problem so im updated mysql to 8.0.30 and now working perfect
